Automated Modular Benchmarking System: DiffPoseTemporal
DiffPoseTemporal
Compute difference in a pose value from a topic between start and stop.
#include "diff_pose_temporal.h"
Public Member Functions
DiffPoseTemporal ()
DiffPoseTemporal (ros::NodeHandle nh, std::string node_name)
~DiffPoseTemporal ()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseCalculator
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Private Member Functions
void executeCB () override
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
void printPose (geometry_msgs::PoseStamped pose)
Print pose values. Debug only.
Private Attributes
ambs_loggers::DebugLogger debug_logger_
const std::string DIFF_ORIENTATION = "out_diff_orientation"
const std::string DIFF_POSITION_ = "out_diff_position"
ambs_base::AMBSTemplatedInterface< std_msgs::Float64 > float_interface_
const std::string IN_POSE_ = "in_pose"
ambs_base::AMBSTemplatedInterface< geometry_msgs::PoseStamped > pose_interface_
std_msgs::Float64 result_msg_
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseCalculator
template<typename T >
T getResolvedParam (std::string param_name, T default_value=T())
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the thread. MUST BE EXPLICITLY CALLED.
void threadCB ()
Thread function. Runs calculator logic at.
Protected Attributes inherited from AMBSBaseCalculator
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Detailed Description
Compute difference in a pose value from a topic between start and stop.
Has standard control intetrface, a pose interface with one input and a float interface with one output port
Constructor & Destructor Documentation
DiffPoseTemporal() [1/2]
DiffPoseTemporal () inline
{}
~DiffPoseTemporal()
~DiffPoseTemporal () inline
{}
DiffPoseTemporal() [2/2]
DiffPoseTemporal (ros::NodeHandle nh, std::string node_name) inline
                                                         :
    ambs_base::AMBSBaseCalculator(nh, node_name)
  {}
Member Function Documentation
executeCB()
void executeCB () override private virtual
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Parameters
event Not used
Implements AMBSBaseCalculator.
{
  std_msgs::Float64 diff_pos_msg;
  std_msgs::Float64 diff_orientation_msg;
  default_control_.waitForStart();
  geometry_msgs::PoseStamped start_pose = pose_interface_.getPortMsg(IN_POSE_);
  ROS_DEBUG_STREAM(node_name_ << ": Starting pos stamp @ " <<  start_pose.header.stamp
                      << " stored @ " << ros::Time::now() <<
                    ": " << start_pose.pose.position.x);
  ROS_DEBUG_STREAM(" ");
  default_control_.waitForStop();
  geometry_msgs::PoseStamped stop_pose = pose_interface_.getPortMsg(IN_POSE_);
  ROS_DEBUG_STREAM(node_name_ << ": Stopping pos stamp @ " <<  stop_pose.header.stamp
                   << " stored @ " << ros::Time::now() <<
                    ": " << stop_pose.pose.position.x);
  ROS_DEBUG_STREAM(" ");
  diff_pos_msg.data = ambs_helper::getTranslationDiffFromPoses(start_pose, stop_pose);
  diff_orientation_msg.data = ambs_helper::getYawDiffFromPoses(start_pose, stop_pose);
  ROS_INFO_STREAM(node_name_ << ": Diff Pos: " << diff_pos_msg.data << " Diff Ori: " << diff_orientation_msg.data);
  float_interface_.publishMsgOnPort(DIFF_POSITION_, diff_pos_msg);
  float_interface_.publishMsgOnPort(DIFF_ORIENTATION, diff_orientation_msg);
  default_control_.publishDone();
  debug_logger_.logInfo("Lin: " + std::to_string(diff_pos_msg.data));
  debug_logger_.logInfo("Ang(deg): " + std::to_string(diff_orientation_msg.data));
  default_control_.waitForReset();
  float_interface_.resetAllPorts();
  pose_interface_.resetAllPorts();
  ROS_INFO_STREAM(node_name_ << ": Restarting calculator");
  ROS_DEBUG_STREAM(" ");
  ROS_DEBUG_STREAM("-----------------------------------------------------------");
  ROS_DEBUG_STREAM(" ");
}
References DiffPoseTemporal::debug_logger_, AMBSBaseCalculator::default_control_, DiffPoseTemporal::DIFF_ORIENTATION, DiffPoseTemporal::DIFF_POSITION_, DiffPoseTemporal::float_interface_, ambs_helper::getTranslationDiffFromPoses(), ambs_helper::getYawDiffFromPoses(), DiffPoseTemporal::IN_POSE_, DebugLogger::logInfo(), AMBSBaseCalculator::node_name_, DiffPoseTemporal::pose_interface_, AMBSDefaultCalculatorInterface::publishDone(), AMBSDefaultCalculatorInterface::waitForReset(), AMBSDefaultCalculatorInterface::waitForStart(), and AMBSDefaultCalculatorInterface::waitForStop().
init()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseCalculator::startCalculator() spawns a timer which executes executeCB()
{
  std::vector<std::string> float_inputs{};
  std::vector<std::string> float_outputs{DIFF_POSITION_, DIFF_ORIENTATION};
  float_interface_.init(float_inputs, float_outputs, nh_, node_name_);
  std::vector<std::string> pose_inputs{IN_POSE_};
  std::vector<std::string> pose_outputs{};
  pose_interface_.init(pose_inputs, pose_outputs, nh_, node_name_);
  debug_logger_.init(nh_, node_name_);
  startCalculator();
}
References DiffPoseTemporal::debug_logger_, DiffPoseTemporal::DIFF_ORIENTATION, DiffPoseTemporal::DIFF_POSITION_, DiffPoseTemporal::float_interface_, DiffPoseTemporal::IN_POSE_, DebugLogger::init(), AMBSBaseCalculator::nh_, AMBSBaseCalculator::node_name_, DiffPoseTemporal::pose_interface_, and AMBSBaseCalculator::startCalculator().
printPose()
void printPose (geometry_msgs::PoseStamped pose) private
Print pose values. Debug only.
Parameters
pose Pose to print
{
  ROS_INFO_STREAM(node_name_ << ": (" << pose.pose.position.x << ", "
                                      << pose.pose.position.y << ", "
                                      << pose.pose.position.z << ") ("
                                      << ambs_helper::getYawDegreesFromQuaternion(pose.pose.orientation) << " deg)");
}
References ambs_helper::getYawDegreesFromQuaternion(), and AMBSBaseCalculator::node_name_.
The documentation for this class was generated from the following file:
ambs_components/include/ambs_components/ambs_calculators/differentiators/diff_pose_temporal.h