Automated Modular Benchmarking System: ambs_tests/test/unit_tests/core/helper/test_helper.cpp File Reference
test_helper.cpp File Reference
#include <gtest/gtest.h>
#include <string>
#include <vector>
#include <ros/ros.h>
#include <std_msgs/Float64.h>
#include "ambs_core/ambs_helper/helper.h"
Classes
class TestHelper
Functions
int main (int argc, char **argv)
TEST_F (TestHelper, test_maxdev)
TEST_F (TestHelper, test_mean)
TEST_F (TestHelper, test_stdev)
Function Documentation
main()
int main (int argc, char ** argv)
{
    testing::InitGoogleTest(&argc, argv);
    ros::init(argc, argv, "test_float_param_comp");
    ros::AsyncSpinner spinner(1);
    spinner.start();
    int ret = RUN_ALL_TESTS();
    spinner.stop();
    ros::shutdown();
    return ret;
}
TEST_F() [1/3]
TEST_F (TestHelper , test_maxdev)
{
  EXPECT_DOUBLE_EQ(ambs_helper::getMaxDeviation(data_list_1), maxdev_dl_1);
}
References ambs_helper::getMaxDeviation().
TEST_F() [2/3]
TEST_F (TestHelper , test_mean)
{
  EXPECT_DOUBLE_EQ(ambs_helper::getMean(data_list_1), avg_dl_1);
}
References ambs_helper::getMean().
TEST_F() [3/3]
TEST_F (TestHelper , test_stdev)
{
  EXPECT_DOUBLE_EQ(ambs_helper::getStandardDeviation(data_list_1), std_dl_1);
  EXPECT_NEAR(ambs_helper::getStandardDeviation(data_list_1), std_dl_1, 0.01);
}
References ambs_helper::getStandardDeviation().