Automated Modular Benchmarking System: OrGate
OrGate
N Input OR Gate - 'nuff said.
#include "or_gate.h"
Public Member Functions
OrGate ()
OrGate (ros::NodeHandle nh, std::string node_name)
~OrGate ()
void init (std::string in_start, std::string in_stop, std::string in_reset, std::string out_done, std::string out_signal)
init function will be called by nodelet, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseCalculator
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Private Member Functions
void executeCB () override
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Private Attributes
std::vector< std::string > bool_inputs_
ambs_base::AMBSBooleanInterface bool_interface_
int n_inputs_ = 3
ros::NodeHandle nh_
std::string OUT_RESULT_ = "out_signal"
std::string PARAM_N_INPUTS_ = "n_inputs"
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseCalculator
template<typename T >
T getResolvedParam (std::string param_name, T default_value=T())
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the thread. MUST BE EXPLICITLY CALLED.
void threadCB ()
Thread function. Runs calculator logic at.
Protected Attributes inherited from AMBSBaseCalculator
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Detailed Description
N Input OR Gate - 'nuff said.
Takes param 'n_inputs' once during init and dynamically spawns as many inputs in runtime.
Constructor & Destructor Documentation
OrGate() [1/2]
OrGate () inline
{}
~OrGate()
~OrGate () inline
{}
OrGate() [2/2]
OrGate (ros::NodeHandle nh, std::string node_name) inline
                                               :
    ambs_base::AMBSBaseCalculator(nh, node_name),
    nh_(nh)
  {}
Member Function Documentation
executeCB()
void executeCB () override private virtual
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Parameters
event Not used
Implements AMBSBaseCalculator.
{
  default_control_.waitForStart();
  ros::Rate loop(100);
  while (ros::ok())
  {
    loop.sleep();
    if (default_control_.getStopMsg().data)
    {
      ROS_INFO_STREAM(node_name_ << ": Got stop");
      break;
    }
    for (std::string port : bool_inputs_)
    {
      if (bool_interface_.getPortMsg(port).data)
      {
        bool_interface_.publishMsgOnPort(OUT_RESULT_, bool_interface_.constructNewBoolStamped(true));
        bool_interface_.resetAllPorts();
      }
    }
  }
  bool_interface_.resetAllPorts();
  default_control_.publishDone();
  default_control_.waitForReset();
  ROS_INFO_STREAM(node_name_ << ": Restarting calculator");
}
References OrGate::bool_inputs_, OrGate::bool_interface_, AMBSBooleanInterface::constructNewBoolStamped(), AMBSBaseCalculator::default_control_, AMBSTemplatedInterface< T >::getPortMsg(), AMBSDefaultCalculatorInterface::getStopMsg(), AMBSBaseCalculator::node_name_, OrGate::OUT_RESULT_, AMBSDefaultCalculatorInterface::publishDone(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSTemplatedInterface< T >::resetAllPorts(), AMBSDefaultCalculatorInterface::waitForReset(), and AMBSDefaultCalculatorInterface::waitForStart().
init()
void init (std::string in_start = "in_start", std::string in_stop = "in_stop", std::string in_reset = "in_reset", std::string out_done = "out_done", std::string out_signal = "out_signal")
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseCalculator::startCalculator() spawns a timer which executes executeCB()
{
  OUT_RESULT_ = out_signal;
  n_inputs_ = getResolvedParam<int>(PARAM_N_INPUTS_, n_inputs_);
  if (n_inputs_ < 2)
  {
    ROS_ERROR_STREAM(node_name_ + ": Param " << PARAM_N_INPUTS_ << "<2, makes no sense");
    throw std::invalid_argument(node_name_ + ": Param " + PARAM_N_INPUTS_ + "<2, makes no sense");
  }
  for (int i = 1; i <= n_inputs_; i++)
  {
    bool_inputs_.push_back("in_input_"+std::to_string(i));
  }
  std::vector<std::string> bool_outputs{OUT_RESULT_};
  bool_interface_.init(bool_inputs_, bool_outputs, nh_, node_name_);
  startCalculator();
}
References OrGate::bool_inputs_, OrGate::bool_interface_, AMBSTemplatedInterface< T >::init(), OrGate::n_inputs_, OrGate::nh_, AMBSBaseCalculator::node_name_, OrGate::OUT_RESULT_, OrGate::PARAM_N_INPUTS_, and AMBSBaseCalculator::startCalculator().
The documentation for this class was generated from the following file:
ambs_components/include/ambs_components/ambs_calculators/utils/or_gate.h