Automated Modular Benchmarking System: ambs_helper Namespace Reference
ambs_helper Namespace Reference
Functions
double getMaxDeviation (std::vector< double > data)
Get Maximum Deviation of a data series.
double getMean (std::vector< double > data)
Get mean of a data series.
double getStandardDeviation (std::vector< double > data)
Get Standard Deviation of a data series.
double getTranslationDiffFromPoses (geometry_msgs::PoseStamped start_pose, geometry_msgs::PoseStamped stop_pose)
double getYawDegreesFromQuaternion (geometry_msgs::Quaternion orientation)
double getYawDiffFromPoses (geometry_msgs::PoseStamped start_pose, geometry_msgs::PoseStamped stop_pose)
Function Documentation
getMaxDeviation()
double ambs_helper::getMaxDeviation (std::vector< double > data)
Get Maximum Deviation of a data series.
Parameters
data The data series
Returns
The MD
{
  double mean = getMean(data);
  double md = 0;
  for (double val : data)
  {
    md = std::max(md, std::abs(val - mean));
  }
  return md;
}
References getMean().
Referenced by BenchBraking::executeCB(), and TEST_F().
getMean()
double ambs_helper::getMean (std::vector< double > data)
Get mean of a data series.
Parameters
data The data series
Returns
The mean
{
  double sum = 0;
  for (double val : data)
  {
    sum += val;
  }
  double mean = sum/data.size();
  return mean;
}
Referenced by BenchBraking::executeCB(), getMaxDeviation(), getStandardDeviation(), and TEST_F().
getStandardDeviation()
double ambs_helper::getStandardDeviation (std::vector< double > data)
Get Standard Deviation of a data series.
Parameters
data The data series
Returns
The SD
{
  double mean = getMean(data);
  double sd = 0;
  for (double val : data)
  {
    sd += pow(val - mean, 2);
  }
  return sqrt(sd/data.size());
}
References getMean().
Referenced by BenchBraking::executeCB(), and TEST_F().
getTranslationDiffFromPoses()
double ambs_helper::getTranslationDiffFromPoses (geometry_msgs::PoseStamped start_pose, geometry_msgs::PoseStamped stop_pose)
{
  double delta_x = std::abs(start_pose.pose.position.x - stop_pose.pose.position.x);
  double delta_y = std::abs(start_pose.pose.position.y - stop_pose.pose.position.y);
  return std::sqrt((delta_x*delta_x) + (delta_y*delta_y));
}
Referenced by DiffPoseTemporal::executeCB().
getYawDegreesFromQuaternion()
double ambs_helper::getYawDegreesFromQuaternion (geometry_msgs::Quaternion orientation)
{
  tf::Quaternion quat;
  quat.normalize();
  double roll, pitch, yaw;
  tf::quaternionMsgToTF(orientation, quat);
  tf::Matrix3x3 mat(quat);
  mat.getRPY(roll, pitch, yaw);
  return angles::to_degrees(yaw);
}
Referenced by getYawDiffFromPoses(), and DiffPoseTemporal::printPose().
getYawDiffFromPoses()
double ambs_helper::getYawDiffFromPoses (geometry_msgs::PoseStamped start_pose, geometry_msgs::PoseStamped stop_pose)
{
  return std::abs(getYawDegreesFromQuaternion(start_pose.pose.orientation) -
        getYawDegreesFromQuaternion(stop_pose.pose.orientation));
}
References getYawDegreesFromQuaternion().
Referenced by DiffPoseTemporal::executeCB().