Automated Modular Benchmarking System: EdgeDetector
EdgeDetector
Monitor a boolean input and output detected rising/falling edges. Cannot detec first falling edge.
#include "edge_detector.h"
Public Member Functions
EdgeDetector ()
EdgeDetector (ros::NodeHandle nh, std::string node_name)
~EdgeDetector ()
void init (std::string in_start, std::string in_stop, std::string in_reset, std::string out_done, std::string in_bool, std::string out_rising, std::string out_falling)
init function will be called by nodelet, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseCalculator
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Private Member Functions
void executeCB (const ros::TimerEvent &event) override
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Private Attributes
ambs_base::AMBSBooleanInterface bool_interface_
std::string IN_BOOL_ = "in_bool"
ros::NodeHandle nh_
std::string OUT_FALLING_ = "out_falling"
std::string OUT_RISING_ = "out_rising"
bool previous_bool_ = false
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseCalculator
template<typename T >
T getResolvedParam (std::string param_name, T default_value=T())
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the timer thread. MUST BE EXPLICITLY CALLED.
Protected Attributes inherited from AMBSBaseCalculator
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Detailed Description
Monitor a boolean input and output detected rising/falling edges. Cannot detec first falling edge.
Has standard control intetrface, and a bool interface with one input and two output ports
Constructor & Destructor Documentation
EdgeDetector() [1/2]
EdgeDetector () inline
{}
~EdgeDetector()
~EdgeDetector () inline
{}
EdgeDetector() [2/2]
EdgeDetector (ros::NodeHandle nh, std::string node_name) inline
                                                     :
    ambs_base::AMBSBaseCalculator(nh, node_name),
    nh_(nh)
  {}
Member Function Documentation
executeCB()
void executeCB (const ros::TimerEvent & event) override private virtual
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Parameters
event Not used
Implements AMBSBaseCalculator.
{
  (void) event;
  default_control_.waitForStart();
  ros::Rate loop(100);
  while (ros::ok())
  {
    loop.sleep();
     if (default_control_.getStopMsg().data)
     {
       ROS_INFO_STREAM(node_name_ << ": Got stop");
       break;
     }
     if (!bool_interface_.isPortValid(IN_BOOL_))
     {
       continue;
     }
     bool current_bool = bool_interface_.getPortMsg(IN_BOOL_).data;
     if (current_bool != previous_bool_)
     {
       if (current_bool)
       {
         ROS_INFO_STREAM(node_name_ << ": Rising edge detected");
         bool_interface_.publishMsgOnPort(OUT_FALLING_, default_control_.constructNewBoolStamped(false));
         bool_interface_.publishMsgOnPort(OUT_RISING_, default_control_.constructNewBoolStamped(true));
       }
       else
       {
         ROS_INFO_STREAM(node_name_ << ": Falling edge detected");
         bool_interface_.publishMsgOnPort(OUT_RISING_, default_control_.constructNewBoolStamped(false));
         bool_interface_.publishMsgOnPort(OUT_FALLING_, default_control_.constructNewBoolStamped(true));
       }
       previous_bool_ = current_bool;
     }
  }
  default_control_.publishDone();
  default_control_.waitForReset();
  bool_interface_.resetAllPorts();
  ROS_INFO_STREAM(node_name_ << ": Restarting calculator");
}
References EdgeDetector::bool_interface_, AMBSBooleanInterface::constructNewBoolStamped(), AMBSBaseCalculator::default_control_, AMBSTemplatedInterface< T >::getPortMsg(), AMBSDefaultCalculatorInterface::getStopMsg(), EdgeDetector::IN_BOOL_, AMBSTemplatedInterface< T >::isPortValid(), AMBSBaseCalculator::node_name_, EdgeDetector::OUT_FALLING_, EdgeDetector::OUT_RISING_, EdgeDetector::previous_bool_, AMBSDefaultCalculatorInterface::publishDone(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSTemplatedInterface< T >::resetAllPorts(), AMBSDefaultCalculatorInterface::waitForReset(), and AMBSDefaultCalculatorInterface::waitForStart().
init()
void init (std::string in_start = "in_start", std::string in_stop = "in_stop", std::string in_reset = "in_reset", std::string out_done = "out_done", std::string in_bool = "in_bool", std::string out_rising = "out_rising", std::string out_falling = "out_falling")
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseCalculator::startCalculator() spawns a timer which executes executeCB()
{
  OUT_RISING_ = out_rising;
  OUT_FALLING_ = out_falling;
  IN_BOOL_ = in_bool;
  std::vector<std::string> bool_inputs{IN_BOOL_};
  std::vector<std::string> bool_outputs{OUT_RISING_, OUT_FALLING_};
  bool_interface_.init(bool_inputs, bool_outputs, nh_, node_name_);
  default_control_.initDefaultInterface(nh_, node_name_, in_start, in_stop, in_reset, out_done);
  startCalculator();
}
References EdgeDetector::bool_interface_, AMBSBaseCalculator::default_control_, EdgeDetector::IN_BOOL_, AMBSTemplatedInterface< T >::init(), AMBSDefaultCalculatorInterface::initDefaultInterface(), EdgeDetector::nh_, AMBSBaseCalculator::node_name_, EdgeDetector::OUT_FALLING_, EdgeDetector::OUT_RISING_, and AMBSBaseCalculator::startCalculator().
The documentation for this class was generated from the following file:
ambs_components/include/ambs_components/ambs_calculators/comparators/edge_detector.h