Automated Modular Benchmarking System: CommandVelocityInterpreter
CommandVelocityInterpreter
Class to convert velocity commands from runner into cmd_vel messages.
#include "velocity_interpreter.h"
Public Member Functions
CommandVelocityInterpreter ()
CommandVelocityInterpreter (ros::NodeHandle nh, std::string node_name)
void init ()
Private Member Functions
geometry_msgs::Twist constructNewTwistWithX (double x)
void executeCB (const ros::TimerEvent &event)
Private Attributes
const std::string ACTIVATE_ = "in_activate"
const std::string CMD_VEL_ = "out_cmd_vel"
ambs_base::AMBSBooleanInterface control_interface_
const std::string DEACTIVATE_ = "in_deactivate"
const double default_velocity_x_ = 0.8
ros::Timer execute_timer_
ros::NodeHandle nh_
std::string node_name_
const std::string PARAM_VEL_X_ = "velocity_x"
const double pub_rate_ = 20
ros::Publisher pub_vel_
const double queue_size = 10
const std::string START_ROBOT_ = "in_start_robot"
const std::string STOP_ROBOT_ = "in_stop_robot"
double velocity_x_
Detailed Description
Class to convert velocity commands from runner into cmd_vel messages.
Ports: Inputs - Activate, Start, Stop, Deactivate Outputs - Cmd_vel
Functionality: All input ports have an internal buffer that saves latest value. Interpreter always works off of latest buffer value. Start & Stop are matched pair, needing to be only one True and one False to work. Starts deactivated state.
Operation: Set Activate=True to enable interpreter If Activated, and if neither Start nor Stop is True, send no velocity If Activated, set (Start=True then Stop=False) to start sending parametrised velocity If Activated, set (Start=False then Stop=True) to start sending 0 velocity If Activated, set Deactivate=True to disable interpreter, send no velocity, clear all buffers & go back to deactivated state.
Constructor & Destructor Documentation
CommandVelocityInterpreter() [1/2]
CommandVelocityInterpreter () inline
{}
CommandVelocityInterpreter() [2/2]
CommandVelocityInterpreter (ros::NodeHandle nh, std::string node_name)
                                                                                           :
  nh_(nh),
  node_name_(node_name)
{}
Member Function Documentation
constructNewTwistWithX()
geometry_msgs::Twist constructNewTwistWithX (double x) private
{
  geometry_msgs::Twist msg;
  msg.linear.x = x;
  return msg;
}
Referenced by CommandVelocityInterpreter::executeCB().
executeCB()
void executeCB (const ros::TimerEvent & event) private
{
  (void) event;
  if (control_interface_.getPortMsg(ACTIVATE_).data &&
      !control_interface_.getPortMsg(DEACTIVATE_).data)
  {
    ROS_DEBUG_STREAM(node_name_ << ": ACTIVATED");
    if (control_interface_.getPortMsg(START_ROBOT_).data &&
        !control_interface_.getPortMsg(STOP_ROBOT_).data)
    {
      ROS_DEBUG_STREAM(node_name_ << ": Pub " << velocity_x_);
      pub_vel_.publish(constructNewTwistWithX(velocity_x_));
    }
    else if (!control_interface_.getPortMsg(START_ROBOT_).data &&
             control_interface_.getPortMsg(STOP_ROBOT_).data)
    {
      ROS_DEBUG_STREAM(node_name_ << ": Pub " << 0);
      pub_vel_.publish(constructNewTwistWithX(0));
    }
    else if (control_interface_.getPortMsg(START_ROBOT_).data &&
             control_interface_.getPortMsg(STOP_ROBOT_).data)
    {
      ROS_DEBUG_STREAM(node_name_ << ": Start & Stop both true!!");
    }
    else
    {
      ROS_DEBUG_STREAM(node_name_ << ": Pub nothing");
    }
    return;
  }
  else if (control_interface_.getPortMsg(ACTIVATE_).data &&
           control_interface_.getPortMsg(DEACTIVATE_).data)
  {
    ROS_INFO_STREAM(node_name_ << ": DEACTIVATED");
    control_interface_.resetAllPorts();
    return;
  }
}
References CommandVelocityInterpreter::ACTIVATE_, CommandVelocityInterpreter::constructNewTwistWithX(), CommandVelocityInterpreter::control_interface_, CommandVelocityInterpreter::DEACTIVATE_, AMBSTemplatedInterface< T >::getPortMsg(), CommandVelocityInterpreter::node_name_, CommandVelocityInterpreter::pub_vel_, AMBSTemplatedInterface< T >::resetAllPorts(), CommandVelocityInterpreter::START_ROBOT_, CommandVelocityInterpreter::STOP_ROBOT_, and CommandVelocityInterpreter::velocity_x_.
Referenced by CommandVelocityInterpreter::init().
init()
void init ()
{
  ROS_INFO_STREAM(node_name_ << ": Interpreter ready");
  std::string param_name = "/ambs/interpreters/" + node_name_ + "/" + PARAM_VEL_X_;
  if (!nh_.param(param_name, velocity_x_, default_velocity_x_))
  {
    ROS_WARN_STREAM(node_name_ << ": Param " << param_name << " not found, defaulting to " << default_velocity_x_);
  }
  std::vector<std::string> inputs{START_ROBOT_, STOP_ROBOT_, ACTIVATE_, DEACTIVATE_};
  std::vector<std::string> outputs{};
  control_interface_.init(inputs, outputs, nh_, node_name_);
  pub_vel_ = nh_.advertise<geometry_msgs::Twist>(CMD_VEL_, 10);
  execute_timer_ = nh_.createTimer(ros::Duration(1/pub_rate_),
                                   boost::bind(&CommandVelocityInterpreter::executeCB, this, _1));
}
References CommandVelocityInterpreter::ACTIVATE_, CommandVelocityInterpreter::CMD_VEL_, CommandVelocityInterpreter::control_interface_, CommandVelocityInterpreter::DEACTIVATE_, CommandVelocityInterpreter::default_velocity_x_, CommandVelocityInterpreter::execute_timer_, CommandVelocityInterpreter::executeCB(), AMBSTemplatedInterface< T >::init(), CommandVelocityInterpreter::nh_, CommandVelocityInterpreter::node_name_, CommandVelocityInterpreter::PARAM_VEL_X_, CommandVelocityInterpreter::pub_rate_, CommandVelocityInterpreter::pub_vel_, CommandVelocityInterpreter::START_ROBOT_, CommandVelocityInterpreter::STOP_ROBOT_, and CommandVelocityInterpreter::velocity_x_.
The documentation for this class was generated from the following files:
ambs_components/include/ambs_components/ambs_interpreters/command_interpreters/velocity_interpreter.h
ambs_components/src/interpreters/command_interpreters/velocity_interpreter.cpp