Automated Modular Benchmarking System: AMBSBooleanInterface
AMBSBooleanInterface
A bool specialisation of AMBSTemplatedInterface. Offers two extra functions.
#include "ambs_boolean_interface.hpp"
Public Member Functions
AMBSBooleanInterface ()
AMBSBooleanInterface (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs)
virtual ~AMBSBooleanInterface ()
ambs_msgs::BoolStamped constructNewBoolStamped (bool data)
Create a new BoolStamped type message.
ambs_msgs::BoolStamped waitForTrueOnPort (std::string port)
Wait for TRUE on a port.
Public Member Functions inherited from AMBSTemplatedInterface< ambs_msgs::BoolStamped >
AMBSTemplatedInterface ()
AMBSTemplatedInterface (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name)
Constructor.
~AMBSTemplatedInterface ()
ambs_msgs::BoolStamped getPortMsg (std::string port_name)
Gets the latest message received from the port, even if it is not a latched topic.
void init (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name)
Initialisation function, decoupled from constructor for convenience.
bool isPortValid (std::string port_name)
Returns if the port has received at least on message.
void printPorts ()
Prints the member fields of the AMBSPorts object of all ports.
void publishMsgOnPort (std::string port_name, ambs_msgs::BoolStamped msg)
Publish a message on a port.
void resetAllPorts ()
Reset inernal buffer message of all ports.
void resetPort (std::string port_name)
Reset internal buffer message of a port.
void setPortMsg (std::string port_name, ambs_msgs::BoolStamped msg)
Sets the internal message value of a port. DOES NOT PUBLISH.
Private Attributes
const double wait_loop_rate = 500
Additional Inherited Members
Protected Member Functions inherited from AMBSTemplatedInterface< ambs_msgs::BoolStamped >
virtual void templatedCB (const boost::shared_ptr< const ambs_msgs::BoolStamped > msg, std::string topic)
The callback function used by ALL ports.
Protected Attributes inherited from AMBSTemplatedInterface< ambs_msgs::BoolStamped >
std::deque< std::condition_variable > cond_vars_
std::map< std::string, AMBSPort< ambs_msgs::BoolStamped > > interfaces_
std::deque< std::mutex > mutexes_
ros::NodeHandle nh_
std::string node_name_
const unsigned int publisher_queue_size_
const unsigned int subscriber_queue_size_
Detailed Description
A bool specialisation of AMBSTemplatedInterface. Offers two extra functions.
Constructor & Destructor Documentation
AMBSBooleanInterface() [1/2]
AMBSBooleanInterface () inline
{}
AMBSBooleanInterface() [2/2]
AMBSBooleanInterface (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs) inline
{
  init(extended_bool_inputs, extended_bool_outputs, nh, node_name);
}
References AMBSTemplatedInterface< ambs_msgs::BoolStamped >::init().
~AMBSBooleanInterface()
virtual ~AMBSBooleanInterface () inline virtual
{}
Member Function Documentation
constructNewBoolStamped()
ambs_msgs::BoolStamped constructNewBoolStamped (bool data) inline
Create a new BoolStamped type message.
Parameters
[in] data The data to be held by the new msg
Returns
msg The message to be returned
{
  ambs_msgs::BoolStamped msg;
  msg.data  = data;
  msg.header = std_msgs::Header();
  msg.header.stamp = ros::Time::now();
  return msg;
}
Referenced by Timer::executeCB(), EdgeDetector::executeCB(), CompFloatParam::executeCB(), OrGate::executeCB(), SignalRepeater::executeCB(), BenchBraking::executeCB(), EmptyRunner::executeCB(), AMBSDefaultCalculatorInterface::getResetMsg(), AMBSDefaultCalculatorInterface::getStartMsg(), AMBSDefaultCalculatorInterface::getStopMsg(), AMBSDefaultCalculatorInterface::publishDone(), TestSP6MNP1RB1::sendPulseOn(), AMBSBaseRunner::startRobot(), AMBSBaseRunner::stopRobot(), AMBSBaseRunner::testCompleted(), AMBSBaseRunner::testFailed(), AMBSBaseRunner::testSucceeded(), and AMBSBaseRunner::waitForStart().
waitForTrueOnPort()
ambs_msgs::BoolStamped waitForTrueOnPort (std::string port) inline
Wait for TRUE on a port.
Parameters
port The port to wait on
Returns
The msg that set TRUE
{
  std::unique_lock<std::mutex> lock(mutexes_[interfaces_[port].index_]);
  cond_vars_[interfaces_[port].index_].wait(lock, [this, port]() -> bool{return getPortMsg(port).data;});
  ambs_msgs::BoolStamped msg = *interfaces_[port].msg_;
  resetPort(port);
  return msg;
}
References AMBSTemplatedInterface< ambs_msgs::BoolStamped >::cond_vars_, AMBSTemplatedInterface< ambs_msgs::BoolStamped >::getPortMsg(), AMBSTemplatedInterface< ambs_msgs::BoolStamped >::interfaces_, AMBSTemplatedInterface< ambs_msgs::BoolStamped >::mutexes_, and AMBSTemplatedInterface< ambs_msgs::BoolStamped >::resetPort().
Referenced by EmptyRunner::executeCB(), AMBSDefaultCalculatorInterface::waitForReset(), AMBSBaseRunner::waitForReset(), AMBSDefaultCalculatorInterface::waitForStart(), AMBSBaseRunner::waitForStart(), and AMBSDefaultCalculatorInterface::waitForStop().
The documentation for this class was generated from the following file:
ambs_core/include/ambs_core/ambs_base_interface/ambs_boolean_interface.hpp