Automated Modular Benchmarking System: TestTimer
TestTimer
Public Member Functions
TestTimer ()
void diagCB (const diagnostic_msgs::DiagnosticArray::ConstPtr msg)
void init (ros::NodeHandle nh)
Public Attributes
std::vector< std::string > bool_inputs_ {DONE_, INTERRUPTED_, TIMED_OUT_}
std::vector< std::string > bool_outputs_ {START_, STOP_, RESET_, ENABLE_, DISABLE_}
ambs_base::AMBSBooleanInterface control_iface
ros::Subscriber debug_sub_
const std::string DISABLE_ = "out_disable"
const std::string DONE_ = "in_done"
const std::string ELAPSED_ = "in_elapsed"
const std::string ENABLE_ = "out_enable"
std::vector< std::string > float_inputs_ {ELAPSED_}
ambs_base::AMBSTemplatedInterface< std_msgs::Float64 > float_interface_
std::vector< std::string > float_outputs_
const std::string INTERRUPTED_ = "in_interrupted"
boost::shared_ptr< std::string > log_msg_
ros::NodeHandle nh_
const std::string RESET_ = "out_reset"
const double response_time_ = 0.05
const double spawn_time_ = 0.5
const std::string START_ = "out_start"
const std::string STOP_ = "out_stop"
const std::string TIMED_OUT_ = "in_timed_out"
Detailed Description
Constructor & Destructor Documentation
TestTimer()
TestTimer () inline
{}
Member Function Documentation
diagCB()
void diagCB (const diagnostic_msgs::DiagnosticArray::ConstPtr msg)
{
  // Specific to this test only. Assuming that the first debug msg is from the tested timer.
  *log_msg_ = msg->status[0].message;
}
References log_msg_.
Referenced by init().
init()
void init (ros::NodeHandle nh)
{
  nh_ = nh;
  control_iface.init(bool_inputs_, bool_outputs_, nh_, ros::this_node::getName());
  float_interface_.init(float_inputs_, float_outputs_, nh_, ros::this_node::getName());
  log_msg_.reset(new std::string());
  debug_sub_ =
      nh_.subscribe("/ambs/debug_messages",1000,&TestTimer::diagCB, this);
}
References bool_inputs_, bool_outputs_, control_iface, debug_sub_, diagCB(), float_inputs_, float_interface_, float_outputs_, AMBSTemplatedInterface< T >::init(), log_msg_, and nh_.
The documentation for this class was generated from the following file:
ambs_tests/test/unit_tests/calculators/differentiators/test_timer.cpp