Automated Modular Benchmarking System: SignalRepeater
SignalRepeater
Boost a signal to a certain frequency.
#include "signal_repeater.h"
Public Member Functions
SignalRepeater ()
SignalRepeater (ros::NodeHandle nh, std::string node_name)
~SignalRepeater ()
void init (std::string in_start, std::string in_stop, std::string in_reset, std::string out_done, std::string in_signal, std::string out_signal)
init function will be called by nodelet, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseCalculator
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Private Member Functions
void executeCB () override
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Private Attributes
ambs_base::AMBSBooleanInterface bool_interface_
const int DEFAULT_RATE_ = 20
std::string IN_SIGNAL_ = "in_signal"
ros::NodeHandle nh_
std::string OUT_SIGNAL_ = "out_signal"
const std::string RATE_ = "boost_rate"
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseCalculator
template<typename T >
T getResolvedParam (std::string param_name, T default_value=T())
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the thread. MUST BE EXPLICITLY CALLED.
void threadCB ()
Thread function. Runs calculator logic at.
Protected Attributes inherited from AMBSBaseCalculator
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Detailed Description
Boost a signal to a certain frequency.
Todo:
Make this work with any type of topic (Possible?). Check if boosting up or down.
Constructor & Destructor Documentation
SignalRepeater() [1/2]
SignalRepeater () inline
{}
~SignalRepeater()
~SignalRepeater () inline
{}
SignalRepeater() [2/2]
SignalRepeater (ros::NodeHandle nh, std::string node_name) inline
                                                       :
    ambs_base::AMBSBaseCalculator(nh, node_name),
    nh_(nh)
  {}
Member Function Documentation
executeCB()
void executeCB () override private virtual
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Parameters
event Not used
Implements AMBSBaseCalculator.
{
  default_control_.waitForStart();
  ros::Rate loop(getResolvedParam<int>(RATE_, DEFAULT_RATE_));
  while (ros::ok())
  {
    loop.sleep();
    if (default_control_.getStopMsg().data)
    {
      ROS_INFO_STREAM(node_name_ << ": Got stop");
      break;
    }
    bool val_to_pub = bool_interface_.isPortValid(IN_SIGNAL_) ? bool_interface_.getPortMsg(IN_SIGNAL_).data : false;
    bool_interface_.publishMsgOnPort(OUT_SIGNAL_, bool_interface_.constructNewBoolStamped(val_to_pub));
  }
  default_control_.publishDone();
  default_control_.waitForReset();
  ROS_INFO_STREAM(node_name_ << ": Restarting calculator");
}
References SignalRepeater::bool_interface_, AMBSBooleanInterface::constructNewBoolStamped(), AMBSBaseCalculator::default_control_, SignalRepeater::DEFAULT_RATE_, AMBSTemplatedInterface< T >::getPortMsg(), AMBSDefaultCalculatorInterface::getStopMsg(), SignalRepeater::IN_SIGNAL_, AMBSTemplatedInterface< T >::isPortValid(), AMBSBaseCalculator::node_name_, SignalRepeater::OUT_SIGNAL_, AMBSDefaultCalculatorInterface::publishDone(), AMBSTemplatedInterface< T >::publishMsgOnPort(), SignalRepeater::RATE_, AMBSDefaultCalculatorInterface::waitForReset(), and AMBSDefaultCalculatorInterface::waitForStart().
init()
void init (std::string in_start = "in_start", std::string in_stop = "in_stop", std::string in_reset = "in_reset", std::string out_done = "out_done", std::string in_signal = "in_signal", std::string out_signal = "out_signal")
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseCalculator::startCalculator() spawns a timer which executes executeCB()
{
  OUT_SIGNAL_ = out_signal;
  IN_SIGNAL_ = in_signal;
  std::vector<std::string> bool_inputs{IN_SIGNAL_};
  std::vector<std::string> bool_outputs{OUT_SIGNAL_};
  bool_interface_.init(bool_inputs, bool_outputs, nh_, node_name_);
  startCalculator();
}
References SignalRepeater::bool_interface_, SignalRepeater::IN_SIGNAL_, AMBSTemplatedInterface< T >::init(), SignalRepeater::nh_, AMBSBaseCalculator::node_name_, SignalRepeater::OUT_SIGNAL_, and AMBSBaseCalculator::startCalculator().
The documentation for this class was generated from the following file:
ambs_components/include/ambs_components/ambs_calculators/utils/signal_repeater.h