Automated Modular Benchmarking System: AMBSBaseCalculator
AMBSBaseCalculator abstract
The VIRTUAL base class for all calculators to inherit from.
#include "ambs_base_calculator.hpp"
Public Member Functions
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Protected Member Functions
virtual void executeCB ()=0
template<typename T >
T getResolvedParam (std::string param_name, T default_value=T())
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the thread. MUST BE EXPLICITLY CALLED.
void threadCB ()
Thread function. Runs calculator logic at.
Protected Attributes
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Private Attributes
std::thread calc_thread_
const int thread_loop_rate_ = 100
Detailed Description
The VIRTUAL base class for all calculators to inherit from.
Todo:
Add parameter container + setters/getters
Creates a standard_control_ interface of type AMBSStandardControlInterface and a threaded timer to execute calculator logic
Constructor & Destructor Documentation
AMBSBaseCalculator() [1/2]
AMBSBaseCalculator () inline
{}
~AMBSBaseCalculator()
virtual ~AMBSBaseCalculator () inline virtual
{}
AMBSBaseCalculator() [2/2]
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name) inline
Constructor.
startCalculator() MUST BE EXPLICITLY called to start the timer
Parameters
nh NodeHandle received from the nodelet manager
node_name Explicitly necessary becase all nodelets resolve ros::this_node::getName() as nodelet manager
                                                                                   :
  node_name_(node_name),
  nh_(nh)
{
  default_control_.initDefaultInterface(nh_, node_name_);
}
References AMBSBaseCalculator::default_control_, AMBSDefaultCalculatorInterface::initDefaultInterface(), AMBSBaseCalculator::nh_, and AMBSBaseCalculator::node_name_.
Member Function Documentation
executeCB()
virtual void executeCB () protected pure virtual
Implemented in Stopwatch, Timer, EdgeDetector, CompFloatParam, DiffFloatTemporal, DiffPoseTemporal, OrGate, and SignalRepeater.
Referenced by AMBSBaseCalculator::threadCB().
getResolvedParam()
T getResolvedParam (std::string param_name, T default_value = T()) inline protected
Gets a specified parameter by resolving to the ambs/calculators namespace.
Parameters
param_name The parameter to retrieve
Template Parameters
T nh.getParam() supports ONLY STRING, INT, DOUBLE, FLOAT and BOOL or vectors thereof
example: getResolvedParam<std::vector<double>>("some_param")
{
  std::string resolved_name = "/ambs/calculators/" + node_name_ + "/" + param_name;
  if(nh_.hasParam(resolved_name))
  {
    T param_value;
    nh_.getParam(resolved_name, param_value);
    return param_value;
  }
  else
  {
    ROS_WARN_STREAM(node_name_ << ": Could not fetch param "
                    << resolved_name << ", using default " << default_value);
    return default_value;
  }
}
References AMBSBaseCalculator::nh_, and AMBSBaseCalculator::node_name_.
startCalculator()
void startCalculator () inline protected
Starts the thread. MUST BE EXPLICITLY CALLED.
{
  calc_thread_ = std::thread(&AMBSBaseCalculator::threadCB, this);
}
References AMBSBaseCalculator::calc_thread_, and AMBSBaseCalculator::threadCB().
Referenced by DiffFloatTemporal::init(), DiffPoseTemporal::init(), Stopwatch::init(), Timer::init(), EdgeDetector::init(), SignalRepeater::init(), CompFloatParam::init(), and OrGate::init().
threadCB()
void threadCB () inline protected
Thread function. Runs calculator logic at.
Parameters
thread_loop_rate Hz.
{
  while (ros::ok())
  {
    ros::Rate(thread_loop_rate_).sleep();
    executeCB();
  }
}
References AMBSBaseCalculator::executeCB(), and AMBSBaseCalculator::thread_loop_rate_.
Referenced by AMBSBaseCalculator::startCalculator().
The documentation for this class was generated from the following file:
ambs_core/include/ambs_core/ambs_base_calculator/ambs_base_calculator.hpp