Automated Modular Benchmarking System: AMBSBaseRunner
AMBSBaseRunner abstract
The virtual base class for all runners to inherit from.
#include "ambs_base_runner.h"
Public Member Functions
AMBSBaseRunner ()
AMBSBaseRunner (ros::NodeHandle nh, std::string node_name)
virtual ~AMBSBaseRunner ()
Protected Member Functions
virtual void executeCB (const ros::TimerEvent &event)=0
template<typename T >
T getResolvedParam (std::string param_name)
Gets a specified parameter by resolving to the ambs/runners namespace.
bool initialiseBaseRunner (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs)
Actual initialisation function.
void startRobot ()
void startRunner ()
Starts the timer thread. MUST BE EXPLICITLY CALLED.
void stopRobot ()
void testCompleted ()
Publish test results.
void testFailed ()
Publish test results.
void testSucceeded ()
Publish test results.
std::string timedLoopFallbackOnPorts (std::vector< std::string > *ports, double time, double rate)
Returns the first port in list that has a true message, or if timer expires.
std::string timedLoopSequenceOnPorts (std::vector< std::string > *ports, double time, double rate)
Returns the first port in list that has a false message, or if timer expires.
ambs_msgs::BoolStamped waitForReset ()
Wait for TRUE on the RESET port.
ambs_msgs::BoolStamped waitForStart ()
Wait for TRUE on the START port.
Protected Attributes
const std::string DEBUG_TOPIC = "/ambs/debug_messages"
std::string log_folder_path_
std::string log_path_
ros::NodeHandle nh_
std::string node_name_
const std::string PARAM_LOG_FOLDER_ = "/ambs/log_folder"
const std::string PARAM_LOG_ROOT_ = "/ambs/log_folder_root"
const std::string PARAM_ROBOT_NAME_ = "/ambs/robot_name"
const std::string RESET_TEST_ = "in_reset_test"
const std::string ROSBAG_BEGAN_ = "in_rosbag_began"
AMBSBooleanInterface signal_interface_
const std::string START_ROBOT_ = "out_start_robot"
const std::string START_ROSBAG = "out_start_rosbag"
const std::string START_TEST_ = "in_start_test"
const std::string STOP_ROBOT_ = "out_stop_robot"
const std::string TEST_COMPLETED_ = "out_test_completed"
const std::string TEST_FAILED_ = "out_test_failed"
const std::string TEST_SUCCEEDED_ = "out_test_succeeded"
Private Member Functions
int countSubDirectories (std::string path)
Counts the number of subdirectories in a path.
bool createLoggingFolder (std::string path)
Check if param path exists, create it otherwise, then create next logging folder.
void debugCallback (const diagnostic_msgs::DiagnosticArrayConstPtr &msg)
Callback function for debug topic. Log all messages to file in test folder. Has a globally resolved constant topic name.
Private Attributes
std::vector< std::string > bool_inputs_ {START_TEST_, RESET_TEST_, ROSBAG_BEGAN_}
std::vector< std::string > bool_outputs_
ros::Subscriber debug_sub_
ros::Timer execute_timer_
Detailed Description
The virtual base class for all runners to inherit from.
Todo:
Add parameter container + setters/getters
Constructor & Destructor Documentation
AMBSBaseRunner() [1/2]
AMBSBaseRunner () inline
{}
AMBSBaseRunner() [2/2]
AMBSBaseRunner (ros::NodeHandle nh, std::string node_name) inline
                                                       :
    nh_(nh),
    node_name_(node_name)
  {}
~AMBSBaseRunner()
virtual ~AMBSBaseRunner () inline virtual
{}
Member Function Documentation
countSubDirectories()
int countSubDirectories (std::string path) inline private
Counts the number of subdirectories in a path.
Parameters
path Path to check
Returns
int The number of directories
{
  int count = 0;
  boost::filesystem::directory_iterator end_itr;
  for ( boost::filesystem::directory_iterator itr(path);
        itr != end_itr;
        ++itr )
  {
    if (boost::filesystem::is_directory(itr->status()))
    {
      count++;
    }
  }
  return count;
}
Referenced by AMBSBaseRunner::createLoggingFolder().
createLoggingFolder()
bool createLoggingFolder (std::string path) inline private
Check if param path exists, create it otherwise, then create next logging folder.
Parameters
path Root path to create logging folder in
Returns
bool If logging folder was succesfully created
{
  if (!boost::filesystem::exists(path))
  {
    ROS_WARN_STREAM(node_name_ << ": " << path << " does not exist, creating it");
    try
    {
      boost::filesystem::create_directories(path);
    }
    catch (boost::filesystem::filesystem_error err)
    {
      ROS_ERROR_STREAM(node_name_ << ": " << path << " Could not be created : " << err.what());
      return false;
    }
  }
  int count = countSubDirectories(path);
  ROS_DEBUG_STREAM(node_name_ << ": Currently " << std::to_string(count) << " folders, creating next");
  log_folder_path_ = path + "/" + std::to_string(++count);
  boost::filesystem::create_directory(log_folder_path_);
  nh_.setParam(PARAM_LOG_FOLDER_, log_folder_path_);
  ROS_INFO_STREAM(node_name_ << ": Log folder ready: " << log_folder_path_);
  return true;
}
References AMBSBaseRunner::countSubDirectories(), AMBSBaseRunner::log_folder_path_, AMBSBaseRunner::nh_, AMBSBaseRunner::node_name_, and AMBSBaseRunner::PARAM_LOG_FOLDER_.
Referenced by AMBSBaseRunner::initialiseBaseRunner().
debugCallback()
void debugCallback (const diagnostic_msgs::DiagnosticArrayConstPtr & msg) inline private
Callback function for debug topic. Log all messages to file in test folder. Has a globally resolved constant topic name.
Parameters
msg The diagnostic message to be logged to file
{
  std::ofstream debug_file;
  debug_file.open(log_folder_path_ + "/debug.csv", std::ios_base::app);
  debug_file << msg->header.stamp << " , " <<
                msg->status[0].name << " , " <<
                std::to_string(msg->status[0].level) << " , " <<
                msg->status[0].message << " , " << std::endl;
  debug_file.close();
}
References AMBSBaseRunner::log_folder_path_.
Referenced by AMBSBaseRunner::initialiseBaseRunner().
executeCB()
virtual void executeCB (const ros::TimerEvent & event) protected pure virtual
Implemented in EmptyRunner, and Test1Braking.
Referenced by AMBSBaseRunner::startRunner().
getResolvedParam()
T getResolvedParam (std::string param_name) inline protected
Gets a specified parameter by resolving to the ambs/runners namespace.
Parameters
param_name The parameter to retrieve
Template Parameters
T nh.getParam() supports ONLY STRING, INT, DOUBLE, FLOAT and BOOL or vectors thereof
example: getResolvedParam<std::vector<double>>("some_param")
{
  std::string resolved_name = "/ambs/runners/" + node_name_ + "/" + param_name;
  T param_value;
  if (!nh_.getParam(resolved_name, param_value))
  {
    ROS_WARN_STREAM(node_name_ << ": Could not fetch param - " << resolved_name);
  }
  return param_value;
}
References AMBSBaseRunner::nh_, and AMBSBaseRunner::node_name_.
initialiseBaseRunner()
bool initialiseBaseRunner (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs) inline protected
Actual initialisation function.
startRunner() MUST BE EXPLICITLY called to start the timer
Parameters
nh NodeHandle received from the nodelet manager
{
  nh_ = nh;
  node_name_ = node_name;
  bool_inputs_.insert(bool_inputs_.end(), extended_bool_inputs.begin(), extended_bool_inputs.end());
  bool_outputs_.insert(bool_outputs_.end(), extended_bool_outputs.begin(), extended_bool_outputs.end());
  signal_interface_.init(bool_inputs_, bool_outputs_, nh, node_name_);
  std::string log_root;
  std::string robot_name;
  if (!nh_.getParam(PARAM_LOG_ROOT_, log_root))
  {
    ROS_ERROR_STREAM(node_name_ << ": Param " << PARAM_LOG_ROOT_ << " not set!!");
    return false;
  }
  if (!nh_.getParam(PARAM_ROBOT_NAME_, robot_name))
  {
    ROS_ERROR_STREAM(node_name_ << ": Param " << PARAM_ROBOT_NAME_ << " not set!!");
    return false;
  }
  log_path_ = log_root + "/" + robot_name;
  bool result = createLoggingFolder(log_path_);
  if (result)
  {
    std::ofstream debug_file;
    debug_file.open(log_folder_path_ + "/debug.csv", std::ios_base::app);
    debug_file << "TIMESTAMP " << " , " <<
                  "NODE" << " , " <<
                  "LOG LEVEL " << " , " <<
                  "MESSAGE "<< " , " << std::endl;
    debug_file.close();
    debug_sub_ = nh_.subscribe(DEBUG_TOPIC, 1000, &AMBSBaseRunner::debugCallback, this);
  }
  else
  {
    ros::shutdown();
  }
}
References AMBSBaseRunner::bool_inputs_, AMBSBaseRunner::bool_outputs_, AMBSBaseRunner::createLoggingFolder(), AMBSBaseRunner::debug_sub_, AMBSBaseRunner::DEBUG_TOPIC, AMBSBaseRunner::debugCallback(), AMBSTemplatedInterface< T >::init(), AMBSBaseRunner::log_folder_path_, AMBSBaseRunner::log_path_, AMBSBaseRunner::nh_, AMBSBaseRunner::node_name_, AMBSBaseRunner::PARAM_LOG_ROOT_, AMBSBaseRunner::PARAM_ROBOT_NAME_, and AMBSBaseRunner::signal_interface_.
Referenced by EmptyRunner::init(), and Test1Braking::init().
startRobot()
void startRobot () inline protected
{
  signal_interface_.publishMsgOnPort(STOP_ROBOT_, signal_interface_.constructNewBoolStamped(false));
  signal_interface_.publishMsgOnPort(START_ROBOT_, signal_interface_.constructNewBoolStamped(true));
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSBaseRunner::signal_interface_, AMBSBaseRunner::START_ROBOT_, and AMBSBaseRunner::STOP_ROBOT_.
Referenced by Test1Braking::executeCB().
startRunner()
void startRunner () inline protected
Starts the timer thread. MUST BE EXPLICITLY CALLED.
{
  execute_timer_ = nh_.createTimer(ros::Duration(0.1), boost::bind(&AMBSBaseRunner::executeCB, this, _1));
}
References AMBSBaseRunner::execute_timer_, AMBSBaseRunner::executeCB(), and AMBSBaseRunner::nh_.
Referenced by EmptyRunner::init(), and Test1Braking::init().
stopRobot()
void stopRobot () inline protected
{
  signal_interface_.publishMsgOnPort(START_ROBOT_, signal_interface_.constructNewBoolStamped(false));
  signal_interface_.publishMsgOnPort(STOP_ROBOT_, signal_interface_.constructNewBoolStamped(true));
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSBaseRunner::signal_interface_, AMBSBaseRunner::START_ROBOT_, and AMBSBaseRunner::STOP_ROBOT_.
Referenced by Test1Braking::executeCB().
testCompleted()
void testCompleted () inline protected
Publish test results.
{
  signal_interface_.publishMsgOnPort(TEST_COMPLETED_, signal_interface_.constructNewBoolStamped(true));
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSBaseRunner::signal_interface_, and AMBSBaseRunner::TEST_COMPLETED_.
Referenced by AMBSBaseRunner::testFailed().
testFailed()
void testFailed () inline protected
Publish test results.
{
  signal_interface_.publishMsgOnPort(TEST_FAILED_, signal_interface_.constructNewBoolStamped(true));
  signal_interface_.publishMsgOnPort(TEST_SUCCEEDED_, signal_interface_.constructNewBoolStamped(false));
  testCompleted();
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSBaseRunner::signal_interface_, AMBSBaseRunner::TEST_FAILED_, AMBSBaseRunner::TEST_SUCCEEDED_, and AMBSBaseRunner::testCompleted().
Referenced by Test1Braking::executeCB().
testSucceeded()
void testSucceeded () inline protected
Publish test results.
{
  signal_interface_.publishMsgOnPort(TEST_FAILED_, signal_interface_.constructNewBoolStamped(false));
  signal_interface_.publishMsgOnPort(TEST_SUCCEEDED_, signal_interface_.constructNewBoolStamped(true));
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSBaseRunner::signal_interface_, AMBSBaseRunner::TEST_FAILED_, and AMBSBaseRunner::TEST_SUCCEEDED_.
Referenced by Test1Braking::executeCB().
timedLoopFallbackOnPorts()
std::string timedLoopFallbackOnPorts (std::vector< std::string > * ports, double time, double rate = 10) inline protected
Returns the first port in list that has a true message, or if timer expires.
Parameters
ports The ports to scan sequentially
time The time to loop
rate Scan rate. Higher is faster but more taxing. Possible point of optimisation.
Returns
{
  ros::Time start = ros::Time::now();
  ros::Rate loop(rate);
  while (ros::Time::now() - start <= ros::Duration(time))
  {
    for (auto port : *ports)
    {
      if (signal_interface_.getPortMsg(port).data)
      {
        return port;
      }
      loop.sleep();
      ros::spinOnce();
    }
  }
  return "";
}
References AMBSTemplatedInterface< T >::getPortMsg(), and AMBSBaseRunner::signal_interface_.
Referenced by Test1Braking::executeCB().
timedLoopSequenceOnPorts()
std::string timedLoopSequenceOnPorts (std::vector< std::string > * ports, double time, double rate = 10) inline protected
Returns the first port in list that has a false message, or if timer expires.
Parameters
ports The ports to scan sequentially
time The time to loop
rate Scan rate. Higher is faster but more taxing. Possible point of optimisation.
Returns
{
  ros::Time start = ros::Time::now();
  ros::Rate loop(rate);
  while (ros::Time::now() - start <= ros::Duration(time))
  {
    for (auto port : *ports)
    {
      if (!signal_interface_.getPortMsg(port).data)
      {
        return port;
      }
      loop.sleep();
      ros::spinOnce();
    }
  }
  return "";
}
References AMBSTemplatedInterface< T >::getPortMsg(), and AMBSBaseRunner::signal_interface_.
waitForReset()
ambs_msgs::BoolStamped waitForReset () inline protected
Wait for TRUE on the RESET port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ <<  ": Wait for Reset");
  ambs_msgs::BoolStamped msg = signal_interface_.waitForTrueOnPort(RESET_TEST_);
  ROS_INFO_STREAM(node_name_ << ": Got Reset");
  signal_interface_.resetAllPorts();
  return msg;
}
References AMBSBaseRunner::node_name_, AMBSBaseRunner::RESET_TEST_, AMBSTemplatedInterface< T >::resetAllPorts(), AMBSBaseRunner::signal_interface_, and AMBSBooleanInterface::waitForTrueOnPort().
Referenced by Test1Braking::executeCB().
waitForStart()
ambs_msgs::BoolStamped waitForStart () inline protected
Wait for TRUE on the START port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ << ": Wait for Start");
  ambs_msgs::BoolStamped msg = signal_interface_.waitForTrueOnPort(START_TEST_);
  ROS_INFO_STREAM(node_name_ << ": Got Start, waiting for rosbagger to be ready");
  signal_interface_.waitForTrueOnPort(ROSBAG_BEGAN_);
  return msg;
}
References AMBSBaseRunner::node_name_, AMBSBaseRunner::ROSBAG_BEGAN_, AMBSBaseRunner::signal_interface_, AMBSBaseRunner::START_TEST_, and AMBSBooleanInterface::waitForTrueOnPort().
Referenced by Test1Braking::executeCB().
Member Data Documentation
bool_inputs_
std::vector<std::string> bool_inputs_ {START_TEST_, RESET_TEST_, ROSBAG_BEGAN_} private
Referenced by AMBSBaseRunner::initialiseBaseRunner().
bool_outputs_
std::vector<std::string> bool_outputs_ private
Initial value:
{START_ROBOT_, STOP_ROBOT_, START_ROSBAG,
        TEST_COMPLETED_, TEST_SUCCEEDED_, TEST_FAILED_}
Referenced by AMBSBaseRunner::initialiseBaseRunner().
debug_sub_
ros::Subscriber debug_sub_ private
Referenced by AMBSBaseRunner::initialiseBaseRunner().
DEBUG_TOPIC
const std::string DEBUG_TOPIC = "/ambs/debug_messages" protected
Referenced by AMBSBaseRunner::initialiseBaseRunner().
execute_timer_
ros::Timer execute_timer_ private
Referenced by AMBSBaseRunner::startRunner().
log_folder_path_
std::string log_folder_path_ protected
Referenced by AMBSBaseRunner::createLoggingFolder(), AMBSBaseRunner::debugCallback(), and AMBSBaseRunner::initialiseBaseRunner().
log_path_
std::string log_path_ protected
Referenced by AMBSBaseRunner::initialiseBaseRunner().
nh_
ros::NodeHandle nh_ protected
Referenced by AMBSBaseRunner::createLoggingFolder(), AMBSBaseRunner::getResolvedParam(), EmptyRunner::init(), Test1Braking::init(), AMBSBaseRunner::initialiseBaseRunner(), and AMBSBaseRunner::startRunner().
node_name_
std::string node_name_ protected
Referenced by AMBSBaseRunner::createLoggingFolder(), EmptyRunner::executeCB(), Test1Braking::executeCB(), AMBSBaseRunner::getResolvedParam(), EmptyRunner::init(), Test1Braking::init(), AMBSBaseRunner::initialiseBaseRunner(), AMBSBaseRunner::waitForReset(), and AMBSBaseRunner::waitForStart().
PARAM_LOG_FOLDER_
const std::string PARAM_LOG_FOLDER_ = "/ambs/log_folder" protected
Referenced by AMBSBaseRunner::createLoggingFolder().
PARAM_LOG_ROOT_
const std::string PARAM_LOG_ROOT_ = "/ambs/log_folder_root" protected
Referenced by AMBSBaseRunner::initialiseBaseRunner().
PARAM_ROBOT_NAME_
const std::string PARAM_ROBOT_NAME_ = "/ambs/robot_name" protected
Referenced by AMBSBaseRunner::initialiseBaseRunner().
RESET_TEST_
const std::string RESET_TEST_ = "in_reset_test" protected
Referenced by AMBSBaseRunner::waitForReset().
ROSBAG_BEGAN_
const std::string ROSBAG_BEGAN_ = "in_rosbag_began" protected
Referenced by EmptyRunner::executeCB(), and AMBSBaseRunner::waitForStart().
signal_interface_
AMBSBooleanInterface signal_interface_ protected
Referenced by EmptyRunner::executeCB(), Test1Braking::executeCB(), AMBSBaseRunner::initialiseBaseRunner(), AMBSBaseRunner::startRobot(), AMBSBaseRunner::stopRobot(), AMBSBaseRunner::testCompleted(), AMBSBaseRunner::testFailed(), AMBSBaseRunner::testSucceeded(), AMBSBaseRunner::timedLoopFallbackOnPorts(), AMBSBaseRunner::timedLoopSequenceOnPorts(), AMBSBaseRunner::waitForReset(), and AMBSBaseRunner::waitForStart().
START_ROBOT_
const std::string START_ROBOT_ = "out_start_robot" protected
Referenced by AMBSBaseRunner::startRobot(), and AMBSBaseRunner::stopRobot().
START_ROSBAG
const std::string START_ROSBAG = "out_start_rosbag" protected
Referenced by EmptyRunner::executeCB().
START_TEST_
const std::string START_TEST_ = "in_start_test" protected
Referenced by AMBSBaseRunner::waitForStart().
STOP_ROBOT_
const std::string STOP_ROBOT_ = "out_stop_robot" protected
Referenced by AMBSBaseRunner::startRobot(), and AMBSBaseRunner::stopRobot().
TEST_COMPLETED_
const std::string TEST_COMPLETED_ = "out_test_completed" protected
Referenced by AMBSBaseRunner::testCompleted().
TEST_FAILED_
const std::string TEST_FAILED_ = "out_test_failed" protected
Referenced by AMBSBaseRunner::testFailed(), and AMBSBaseRunner::testSucceeded().
TEST_SUCCEEDED_
const std::string TEST_SUCCEEDED_ = "out_test_succeeded" protected
Referenced by AMBSBaseRunner::testFailed(), and AMBSBaseRunner::testSucceeded().
The documentation for this class was generated from the following file:
ambs_core/include/ambs_core/ambs_base_runner/ambs_base_runner.h