calculators:
  calc_robot_has_max_vel:
    param: 0.5
    tolerance: 0.01

  calc_robot_is_stationary:
    param: 0.0
    tolerance: 0.01

  test_comp_float_temporal:
    thresh_position: 0.5
    thresh_yaw_degrees: 10

runners:
  test1_braking:
    stabilization_timeout: 0.5
    acceleration_timeout: 10
    verification_timeout: 2
    decceleration_timeout: 3

interpreters:
  velocity_interpreter:
    velocity_x: 0.5

test1_rosbagger:
  whitelist:
  # Default whitelist: ["ambs"]
  # Any topics which have one of these STRINGS in them will be added to the whitelist for recording,
    - hedge
    - ros
  blacklist:
  # Any WHITELISTED topics which have one of these STRINGS in them will be rejected for recording
    - compressed
