Automated Modular Benchmarking System: DebugLogger
DebugLogger
Components may use objects of this class to send debug logging messages to the runner.
#include "debug_logger.h"
Public Member Functions
DebugLogger ()
void init (ros::NodeHandle nh, std::string node_name)
void logError (std::string message)
Log message with level 2.
void logInfo (std::string message)
Log message with level 0.
void logWarn (std::string message)
Log message with level 1.
Private Member Functions
diagnostic_msgs::DiagnosticArray constructDiagArrMsg (int8_t level, std::string message)
Private Attributes
ros::Publisher debug_publisher_
const std::string DEBUG_TOPIC = "/ambs/debug_messages"
ros::NodeHandle nh_
std::string node_name_
Detailed Description
Components may use objects of this class to send debug logging messages to the runner.
Constructor & Destructor Documentation
DebugLogger()
DebugLogger () inline
{}
Member Function Documentation
constructDiagArrMsg()
diagnostic_msgs::DiagnosticArray constructDiagArrMsg (int8_t level, std::string message) private
{
  diagnostic_msgs::DiagnosticArray msg;
  diagnostic_msgs::DiagnosticStatus status;
  msg.header.stamp = ros::Time::now();
  status.level = level;
  status.message = message;
  status.name = node_name_;
  msg.status.push_back(status);
  return msg;
}
References DebugLogger::node_name_.
Referenced by DebugLogger::logError(), DebugLogger::logInfo(), and DebugLogger::logWarn().
init()
void init (ros::NodeHandle nh, std::string node_name)
{
  nh_ = nh;
  node_name_ = node_name;
  debug_publisher_ = nh_.advertise<diagnostic_msgs::DiagnosticArray>(DEBUG_TOPIC, 10);
}
References DebugLogger::debug_publisher_, DebugLogger::DEBUG_TOPIC, DebugLogger::nh_, and DebugLogger::node_name_.
Referenced by DiffPoseTemporal::init(), Stopwatch::init(), and BenchBraking::init().
logError()
void logError (std::string message)
Log message with level 2.
Parameters
message Message to log
{
  debug_publisher_.publish(constructDiagArrMsg(diagnostic_msgs::DiagnosticStatus::ERROR, message));
}
References DebugLogger::constructDiagArrMsg(), and DebugLogger::debug_publisher_.
logInfo()
void logInfo (std::string message)
Log message with level 0.
Parameters
message Message to log
{
  debug_publisher_.publish(constructDiagArrMsg(diagnostic_msgs::DiagnosticStatus::OK, message));
}
References DebugLogger::constructDiagArrMsg(), and DebugLogger::debug_publisher_.
Referenced by Stopwatch::executeCB(), and DiffPoseTemporal::executeCB().
logWarn()
void logWarn (std::string message)
Log message with level 1.
Parameters
message Message to log
{
  debug_publisher_.publish(constructDiagArrMsg(diagnostic_msgs::DiagnosticStatus::WARN, message));
}
References DebugLogger::constructDiagArrMsg(), and DebugLogger::debug_publisher_.
The documentation for this class was generated from the following files:
ambs_components/include/ambs_components/ambs_loggers/debug_logger.h
ambs_components/src/loggers/debug_logger.cpp