Automated Modular Benchmarking System: AMBSTemplatedInterface< T >
AMBSTemplatedInterface< T >
The base templated class used to create interfaces for components.
#include "ambs_base_interface.hpp"
Public Member Functions
AMBSTemplatedInterface ()
AMBSTemplatedInterface (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name)
Constructor.
~AMBSTemplatedInterface ()
T getPortMsg (std::string port_name)
Gets the latest message received from the port, even if it is not a latched topic.
void init (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name)
Initialisation function, decoupled from constructor for convenience.
bool isPortValid (std::string port_name)
Returns if the port has received at least on message.
void printPorts ()
Prints the member fields of the AMBSPorts object of all ports.
void publishMsgOnPort (std::string port_name, T msg)
Publish a message on a port.
void resetAllPorts ()
Reset inernal buffer message of all ports.
void resetPort (std::string port_name)
Reset internal buffer message of a port.
void setPortMsg (std::string port_name, T msg)
Sets the internal message value of a port. DOES NOT PUBLISH.
Protected Member Functions
virtual void templatedCB (const boost::shared_ptr< const T > msg, std::string topic)
The callback function used by ALL ports.
Protected Attributes
std::deque< std::condition_variable > cond_vars_
std::map< std::string, AMBSPort< T > > interfaces_
std::deque< std::mutex > mutexes_
ros::NodeHandle nh_
std::string node_name_
const unsigned int publisher_queue_size_ = 10
const unsigned int subscriber_queue_size_ = 10
Detailed Description
template<typename T>
class ambs_base::AMBSTemplatedInterface< T >
The base templated class used to create interfaces for components.
Can be used to create any and all types of interfaces using ROS messages as template types. Utilizes AMBSPort to form interfaces
Ex: A float interface can be created with 2 input ports and 1 output port (ie topics), with each port represented as an AMBSPorts object.
Template Parameters
T The type of interface
Constructor & Destructor Documentation
AMBSTemplatedInterface() [1/2]
AMBSTemplatedInterface () inline
{};
~AMBSTemplatedInterface()
~AMBSTemplatedInterface () inline
{};
AMBSTemplatedInterface() [2/2]
AMBSTemplatedInterface (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name) inline
Constructor.
Call init()
Parameters
input_interface List of names of topics of ports to serve as subscribers
output_interface List of name of topics of ports to serve as publishers
nh Nodehandle passed down from the nodelet manager
node_name Explicitly necessary becase all nodelets resolve ros::this_node::getName() as nodelet manager
{
  init(input_interface, output_interface, nh, node_name);
}
Member Function Documentation
getPortMsg()
T getPortMsg (std::string port_name) inline
Gets the latest message received from the port, even if it is not a latched topic.
Parameters
port_name The name of the topic of the port
TODO: Keep this warning approach or not? Should this function be changed?
{
  T default_msg;
  if(isPortValid(port_name))
  {
    return *interfaces_[port_name].msg_;
  }
  else
  {
//    ROS_WARN_STREAM(node_name_ << ": Trying to get msg on port " << port_name << " but it is null!");
    return default_msg;
  }
}
Referenced by EdgeDetector::executeCB(), OrGate::executeCB(), SignalRepeater::executeCB(), CommandVelocityInterpreter::executeCB(), Test1Braking::executeCB(), Timer::getNextState(), AMBSBaseRunner::timedLoopFallbackOnPorts(), and AMBSBaseRunner::timedLoopSequenceOnPorts().
init()
void init (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name) inline
Initialisation function, decoupled from constructor for convenience.
Create subscribers for inputs ports, publishers for output ports, set node handle and save nodelet name
Parameters
input_interface List of names of topics of ports to serve as subscribers
output_interface List of name of topics of ports to serve as publishers
nh Nodehandle passed down from the nodelet manager
node_name Explicitly necessary becase all nodelets resolve ros::this_node::getName() as nodelet manager
{
  node_name_ = node_name;
  nh_ = nh;
  mutexes_.resize(input_interface.size() + output_interface.size());
  cond_vars_.resize(input_interface.size() + output_interface.size());
  for(unsigned long i=0; i<input_interface.size(); i++)
  {
    AMBSPort<T> port(input_interface[i]);
    port.index_ = i;
    port.sub_ = nh_.subscribe<T>(port.topic_name_, subscriber_queue_size_,
                              boost::bind(&AMBSTemplatedInterface<T>::templatedCB, this,_1, port.topic_name_)
                              );
    interfaces_[port.topic_name_] = port;
  }
  for(unsigned long i=0; i<output_interface.size(); i++)
  {
    AMBSPort<T> port(output_interface[i]);
    port.index_ = i + input_interface.size();
    port.pub_ = nh_.advertise<T>(port.topic_name_, publisher_queue_size_);
    interfaces_[port.topic_name_] = port;
  }
}
References AMBSPort< T >::index_, AMBSPort< T >::pub_, AMBSPort< T >::sub_, and AMBSPort< T >::topic_name_.
Referenced by Timer::init(), CommandVelocityInterpreter::init(), TestSP6MNP1RB1::init(), TestEdgeDetector::init(), TestDiffFloatTemporal::init(), TestDiffPoseTemporal::init(), TestStopwatch::init(), TestTimer::init(), TestOrGate::init(), TestSignalRepeater::init(), TestCompFloatParam::init(), EdgeDetector::init(), SignalRepeater::init(), CompFloatParam::init(), OrGate::init(), and AMBSBaseRunner::initialiseBaseRunner().
isPortValid()
bool isPortValid (std::string port_name)
Returns if the port has received at least on message.
Parameters
port_name Port to check
{
  bool result;
  try
  {
    result = interfaces_[port_name].msg_ != nullptr;
  }
  catch (std::exception e)
  {
    ROS_ERROR_STREAM(node_name_ << ":  isPortValid exception on port " << port_name << " " << e.what());
  }
  return result;
}
Referenced by EdgeDetector::executeCB(), SignalRepeater::executeCB(), AMBSBaseRunner::timedLoopFallbackOnPorts(), and AMBSBaseRunner::timedLoopSequenceOnPorts().
printPorts()
void printPorts inline
Prints the member fields of the AMBSPorts object of all ports.
Used for debugging only
{
   auto iter = interfaces_.begin();
   while(iter != interfaces_.end())
   {
     ROS_INFO_STREAM(node_name_ << " Port: " << iter->first << " Indx: " << iter->second.index_
                     << " Sub: " << iter->second.sub_ << " Pub: " << iter->second.pub_
                     << " Val: " << iter->second.msg_);
     ++iter;
   }
   ROS_INFO_STREAM(node_name_ << " Total: " << interfaces_.size());
}
publishMsgOnPort()
void publishMsgOnPort (std::string port_name, T msg) inline
Publish a message on a port.
Publishes a shared pointer so as to work with nodelet zero copy transfer
Parameters
port_name The name of the topic of the port
T A ROS msg type
msg The msg which is automatically cast into a shared pointer.
{
  try
  {
    setPortMsg(port_name,msg);
    interfaces_[port_name].pub_.publish(boost::make_shared<T>(msg));
  }
  catch (std::exception e)
  {
    ROS_ERROR_STREAM(node_name_ << ":  publishMsgOnPort exception on port " << port_name << " " << e.what());
  }
}
Referenced by Timer::executeCB(), EdgeDetector::executeCB(), CompFloatParam::executeCB(), OrGate::executeCB(), SignalRepeater::executeCB(), BenchBraking::executeCB(), EmptyRunner::executeCB(), TestSP6MNP1RB1::sendPulseOn(), AMBSBaseRunner::startRobot(), AMBSBaseRunner::stopRobot(), AMBSBaseRunner::testCompleted(), AMBSBaseRunner::testFailed(), AMBSBaseRunner::testSucceeded(), and AMBSBaseRunner::waitForStart().
resetAllPorts()
void resetAllPorts inline
Reset inernal buffer message of all ports.
{
  T default_msg;
  auto iter = interfaces_.begin();
  while(iter != interfaces_.end())
  {
    resetPort(iter->first);
    ++iter;
  }
}
Referenced by Timer::executeCB(), EdgeDetector::executeCB(), OrGate::executeCB(), CommandVelocityInterpreter::executeCB(), BenchBraking::executeCB(), and AMBSBaseRunner::waitForReset().
resetPort()
void resetPort (std::string port_name) inline
Reset internal buffer message of a port.
Parameters
port_name Port to reset
{
  try
  {
    interfaces_[port_name].msg_.reset();
  }
  catch (std::exception e)
  {
    ROS_ERROR_STREAM(node_name_ << ":  resetPort exception on port " << port_name << " " << e.what());
  }
}
setPortMsg()
void setPortMsg (std::string port_name, T msg) inline
Sets the internal message value of a port. DOES NOT PUBLISH.
Parameters
port_name The name of the topic of the port
{
  try
  {
    interfaces_[port_name].msg_ = boost::make_shared<T>(msg);
  }
  catch (std::exception e)
  {
    ROS_ERROR_STREAM(node_name_ << ":  setPortMsg exception on port " << port_name << " " << e.what());
  }
}
templatedCB()
void templatedCB (const boost::shared_ptr< const T > msg, std::string topic) inline protected virtual
The callback function used by ALL ports.
Just saves a copy of the received message into the internal buffer in a thread safe manner
Parameters
topic The name of the topic of the port
{
  try
  {
    {
      std::unique_lock<std::mutex> lock(mutexes_[interfaces_[topic].index_]);
      interfaces_[topic].msg_ =  msg;
    }
    cond_vars_[interfaces_[topic].index_].notify_one();
  }
  catch (std::exception e)
  {
    ROS_ERROR_STREAM(node_name_ << ":  templatedCB exception " << e.what());
  }
}
The documentation for this class was generated from the following file:
ambs_core/include/ambs_core/ambs_base_interface/ambs_base_interface.hpp