Automated Modular Benchmarking System: BaseLogger
BaseLogger
Public Member Functions
def __init__ (self, sub_dict={}, result_list=[], param_list=[], rate=100)
def callback (self, msg, key)
def getConfig (self, param_list)
def getSafeFlag (self, key)
def killCommandProc (self)
def logScreenFile (self, log_msg)
def setSafeFlag (self, key, value)
def startCommandProc (self, command)
Public Attributes
command_proc
config_param
result_list
Private Attributes
_config_param
_flag
_input_interface
_locks
_rate
Detailed Description
Constructor & Destructor Documentation
__init__()
def __init__ (self, sub_dict = {}, result_list = [], param_list = [], rate = 100)
Reimplemented in Rosbagger.
    def __init__(self, sub_dict = {}, result_list = [], param_list = [], rate = 100):
        self._rate = rospy.Rate(rate)
        self._input_interface = {
            "start"           : "in_start",
            "stop"            : "in_stop",
            "reset"           : "in_reset"
        }
        self._input_interface.update(sub_dict)
        self._config_param = []
        self._config_param += param_list
        # get ros param:
        self.config_param = {}
        self.getConfig(self._config_param)
        self._locks = {}
        self._flag = {}
        for key in self._input_interface:
            rospy.Subscriber(self._input_interface[key], BoolStamped, self.callback, key)
            self._locks[key] = threading.Lock()
            self._flag[key] = BoolStamped()
            self._flag[key].data = False
        self.result_list = result_list
        for topic in self.result_list:
            rospy.Subscriber(topic, Float64Stamped, self.callback, topic)
            self._locks[topic] = threading.Lock()
            self._flag[topic] = Float64Stamped()
            self._flag[topic].data = float("inf")
References BaseLogger.__init__().
Referenced by BaseLogger.__init__().
Member Function Documentation
callback()
def callback (self, msg, key)
    def callback(self, msg, key):
        self.setSafeFlag(key,msg)
References BaseLogger.callback(), and BaseLogger.setSafeFlag().
Referenced by BaseLogger.callback().
getConfig()
def getConfig (self, param_list)
    def getConfig(self, param_list):
        for arg in param_list:
            if rospy.has_param(arg):
                if arg not in self.config_param:
                    self.config_param[arg] = rospy.get_param(arg)
            else:
                rospy.logerr("{} param not set!!".format(arg))
                rospy.signal_shutdown("param not set")
References BaseLogger.config_param, and BaseLogger.getConfig().
Referenced by BaseLogger.getConfig().
getSafeFlag()
def getSafeFlag (self, key)
    def getSafeFlag(self, key):
        if not key in self._input_interface.keys() and not key in self.result_list:
            rospy.logerr(rospy.get_name() + ": Retrieving a key that does not exist!: {}".format(key))
            return
        else:
            with self._locks[key]:
                return self._flag[key].data
References BaseLogger._flag, BaseLogger._input_interface, BaseLogger._locks, BaseLogger.getSafeFlag(), and BaseLogger.result_list.
Referenced by BaseLogger.getSafeFlag(), and Rosbagger.main_loop().
killCommandProc()
def killCommandProc (self)
    def killCommandProc(self):
        self.command_proc.send_signal(subprocess.signal.SIGINT)
        rospy.loginfo(rospy.get_name() + ": Destructor killing process {}!".format(self.command_proc))
References BaseLogger.command_proc, and BaseLogger.killCommandProc().
Referenced by BaseLogger.killCommandProc(), and Rosbagger.main_loop().
logScreenFile()
def logScreenFile (self, log_msg)
    def logScreenFile(self, log_msg):
        if self.config_param[rospy.get_name() + "/screen"]:
            rospy.logwarn(rospy.get_name() + ": " + log_msg)
            rospy.loginfo(rospy.get_name() + ": " + log_msg)
        else:
            rospy.loginfo(rospy.get_name() + ": " + log_msg)
References BaseLogger.config_param, and BaseLogger.logScreenFile().
Referenced by BaseLogger.logScreenFile().
setSafeFlag()
def setSafeFlag (self, key, value)
    def setSafeFlag(self, key, value):
        if not key in self._input_interface.keys() and not key in self.result_list:
            rospy.logerr(rospy.get_name() + ": Retrieving a key that does not exist!: {}".format(key))
            return
        with self._locks[key]:
            self._flag[key] = value
References BaseLogger._flag, BaseLogger._input_interface, BaseLogger._locks, BaseLogger.result_list, and BaseLogger.setSafeFlag().
Referenced by BaseLogger.callback(), and BaseLogger.setSafeFlag().
startCommandProc()
def startCommandProc (self, command)
    def startCommandProc(self, command):
        # Prepare command
        _command = shlex.split(command)
        self.command_proc = subprocess.Popen(_command)
        rospy.loginfo(rospy.get_name() + ": Starting process {} now!".format(self.command_proc))
References BaseLogger.startCommandProc().
Referenced by Rosbagger.main_loop(), and BaseLogger.startCommandProc().
The documentation for this class was generated from the following file:
ambs_core/src/python_base_classes/base_logger.py