Automated Modular Benchmarking System: TestSP6MNP1RB1
TestSP6MNP1RB1
Public Member Functions
TestSP6MNP1RB1 ()
TestSP6MNP1RB1 (double param, double tolerance)
int getNumberOfRowsInDebugCSV ()
void init (ros::NodeHandle nh)
void sendPulseOn (std::string port, double on_duration)
Public Attributes
const std::string BAG_STARTED_ = "in_rosbag_began"
std::vector< std::string > bool_inputs_ {BAG_STARTED_}
std::vector< std::string > bool_outputs_ {OPEN1_, OPEN2_, CLOSE1_, CLOSE2_, PR1_, PR2_, START_ROBOT_, STOP_ROBOT_}
const std::string CLOSE1_ = "out_close1_busy"
const std::string CLOSE2_ = "out_close2_busy"
ambs_base::AMBSBooleanInterface control_iface
std::string csv_name_
ambs_base::AMBSTemplatedInterface< std_msgs::Float64 > float_interface_
std::string log_folder_
ros::NodeHandle nh_
const std::string OPEN1_ = "out_open1_busy"
const std::string OPEN2_ = "out_open2_busy"
double param_
const std::string PR1_ = "out_pr1_busy"
const std::string PR2_ = "out_pr2_busy"
const double pulse_off_time_ = 0.1
const double response_time = 0.5
const std::string START_ROBOT_ = "out_start_robot"
const std::string STOP_ROBOT_ = "out_stop_robot"
double tolerance_
Detailed Description
Constructor & Destructor Documentation
TestSP6MNP1RB1() [1/2]
TestSP6MNP1RB1 () inline
{}
TestSP6MNP1RB1() [2/2]
TestSP6MNP1RB1 (double param, double tolerance) inline
                                                :
    param_(param),
    tolerance_(tolerance)
  {}
Member Function Documentation
getNumberOfRowsInDebugCSV()
int getNumberOfRowsInDebugCSV ()
{
  std::string s;
  int sTotal = 0;
  std::ifstream in;
  ROS_INFO_STREAM(ros::this_node::getName() << ": Opening file " << csv_name_);
  in.open(csv_name_);
  while (!in.eof())
  {
      getline(in, s);
      ROS_INFO_STREAM(ros::this_node::getName() << ": CSV: " << sTotal << " - " << s);
      sTotal++;
      if (sTotal > 20) break;
  }
  return sTotal-1;  // This always reads one extra line
}
References csv_name_.
init()
void init (ros::NodeHandle nh)
{
  nh_ = nh;
  control_iface.init(bool_inputs_, bool_outputs_, nh_, ros::this_node::getName());
}
References bool_inputs_, bool_outputs_, control_iface, AMBSTemplatedInterface< T >::init(), and nh_.
sendPulseOn()
void sendPulseOn (std::string port, double on_duration)
{
  //  Expecting duration from argv to be in miliseconds
  ROS_INFO_STREAM(ros::this_node::getName() << ": Pulse " << port << " on for " << on_duration/1000);
  ros::Duration(pulse_off_time_/2).sleep();
  control_iface.publishMsgOnPort(port, control_iface.constructNewBoolStamped(true));
  ros::Duration(on_duration/1000).sleep();
  control_iface.publishMsgOnPort(port, control_iface.constructNewBoolStamped(false));
  ros::Duration(pulse_off_time_/2).sleep();
}
References AMBSBooleanInterface::constructNewBoolStamped(), control_iface, AMBSTemplatedInterface< T >::publishMsgOnPort(), and pulse_off_time_.
The documentation for this class was generated from the following file:
ambs_tests/test/integration_tests/denso_use_case/test_sp6mnp1_rb1.cpp