Automated Modular Benchmarking System: Timer
Timer
Start counting down timer from a parametrized value to 0 when triggered and set timed out unless interrupted.
#include "timer.h"
Public Member Functions
Timer ()
Timer (ros::NodeHandle nh, std::string node_name)
~Timer ()
void init ()
init function will be called by nodelet manager, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseCalculator
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Private Member Functions
void disableTimer ()
void executeCB ()
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
TimerState getNextState (TimerState current_state)
Calculate what the next state should be, given current state and external inputs.
Private Attributes
ambs_base::AMBSBooleanInterface control_interface_
TimerState current_state_
ros::Time current_time_
ambs_loggers::DebugLogger debug_logger_
bool debug_states_
const double default_duration_ = 5
const std::string DISABLE_ = "in_disable"
const std::string ELAPSED_ = "out_elapsed"
ros::Duration elapsed_
const std::string ENABLE_ = "in_enable"
ambs_base::AMBSTemplatedInterface< std_msgs::Float64 > float_interface_
const std::string INTERRUPTED_ = "out_interrupted"
TimerState next_state_
ros::NodeHandle nh_
const std::string PARAM_DEBUG_ = "debug_states"
const std::string PARAM_DURATION_ = "duration"
ros::Time start_time_
const std::string TIMED_OUT_ = "out_timed_out"
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseCalculator
template<typename T >
T getResolvedParam (std::string param_name, T default_value=T())
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the thread. MUST BE EXPLICITLY CALLED.
void threadCB ()
Thread function. Runs calculator logic at.
Protected Attributes inherited from AMBSBaseCalculator
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Detailed Description
Start counting down timer from a parametrized value to 0 when triggered and set timed out unless interrupted.
Has standard control intetrface, a float interface with one output port and a Bool interface with two inputs and two outputs.
Constructor & Destructor Documentation
Timer() [1/2]
Timer () inline
{}
~Timer()
~Timer () inline
{}
Timer() [2/2]
Timer (ros::NodeHandle nh, std::string node_name) inline
                                              :
    ambs_base::AMBSBaseCalculator(nh, node_name),
    nh_(nh)
  {}
Member Function Documentation
executeCB()
void executeCB () private virtual
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Parameters
event Not used
Implements AMBSBaseCalculator.
{
  while (ros::ok())
  {
    ros::Rate(100).sleep();
    next_state_ = getNextState(current_state_);
    // Any state -> DISABLED
    if (next_state_ == TimerState::DISABLED)
    {
      if (current_state_ != TimerState::DISABLED)
      {
        ROS_INFO_STREAM(node_name_ << ": DISABLED. Waiting for Enable.");
        if (debug_states_) debug_logger_.logInfo("DISABLED");
      }
      default_control_.resetAllPorts();
      float_interface_.resetAllPorts();
      control_interface_.resetAllPorts();
      current_state_ = TimerState::DISABLED;
    }
    // DISABLED -> IDLE
    else if (current_state_ == TimerState::DISABLED && next_state_ == TimerState::IDLE)
    {
      ROS_INFO_STREAM(node_name_ << ": IDLE. Waiting for Start.");
      current_state_ = TimerState::IDLE;
      if (debug_states_) debug_logger_.logInfo("IDLE");
    }
    // IDLE -> RUNNING
    else if (current_state_ == TimerState::IDLE && next_state_ == TimerState::RUNNING)
    {
       ROS_INFO_STREAM(node_name_ << ": RUNNING. Started timer for "
                      << getResolvedParam<float>(PARAM_DURATION_, default_duration_) << "s. Can interrupt.");
       start_time_ = ros::Time::now();
       current_state_ = TimerState::RUNNING;
       if (debug_states_) debug_logger_.logInfo("RUNNING");
    }
    // RUNNING -> RUNNING
    else if (current_state_ == TimerState::RUNNING && next_state_ == TimerState::RUNNING)
    {
       current_time_ = ros::Time::now();
       elapsed_ = current_time_ - start_time_;
       // RUNNING -> FINISHED - Timed out
       if ( elapsed_ >= ros::Duration(getResolvedParam<float>(PARAM_DURATION_, default_duration_)))
       {
          ROS_INFO_STREAM(node_name_ << ": FINISHED - Timed out. Waiting for reset.");
          std_msgs::Float64 msg;
          msg.data = elapsed_.toSec();
          control_interface_.publishMsgOnPort(TIMED_OUT_, control_interface_.constructNewBoolStamped(true));
          float_interface_.publishMsgOnPort(ELAPSED_, msg);
          default_control_.publishDone();
          current_state_ = TimerState::FINISHED;
          if (debug_states_) debug_logger_.logInfo("FINISHED");
          if (debug_states_) debug_logger_.logInfo("Elapsed " + std::to_string(elapsed_.toSec()));
       }
    }
    // RUNNING -> FINISHED - Interrupted
    else if (current_state_ == TimerState::RUNNING && next_state_ == TimerState::FINISHED)
    {
      ROS_INFO_STREAM(node_name_ << ": FINISHED - Interrupted. Elapsed "
                      << elapsed_.toSec() << "s. Waiting for Reset.");
      std_msgs::Float64 msg;
      msg.data = elapsed_.toSec();
      control_interface_.publishMsgOnPort(INTERRUPTED_, control_interface_.constructNewBoolStamped(true));
      float_interface_.publishMsgOnPort(ELAPSED_, msg);
      default_control_.publishDone();
      current_state_ = TimerState::FINISHED;
      if (debug_states_) debug_logger_.logInfo("FINISHED");
      if (debug_states_) debug_logger_.logInfo("Elapsed " + std::to_string(elapsed_.toSec()));
    }
    // FINISHED -> IDLE
    else if (current_state_ == TimerState::FINISHED && next_state_ == TimerState::IDLE)
    {
      ROS_INFO_STREAM(node_name_ << ": Resetting to IDLE. Waiting for Start.");
      default_control_.resetAllPorts();
      float_interface_.resetAllPorts();
      control_interface_.resetAllPorts();
      current_state_ = TimerState::IDLE;
      if (debug_states_) debug_logger_.logInfo("IDLE");
    }
  }
}
References AMBSBooleanInterface::constructNewBoolStamped(), Timer::control_interface_, Timer::current_state_, Timer::current_time_, Timer::debug_logger_, Timer::debug_states_, AMBSBaseCalculator::default_control_, Timer::default_duration_, ambs_calculators::DISABLED, Timer::ELAPSED_, Timer::elapsed_, ambs_calculators::FINISHED, Timer::float_interface_, Timer::getNextState(), ambs_calculators::IDLE, Timer::INTERRUPTED_, DebugLogger::logInfo(), Timer::next_state_, AMBSBaseCalculator::node_name_, Timer::PARAM_DURATION_, AMBSDefaultCalculatorInterface::publishDone(), AMBSTemplatedInterface< T >::publishMsgOnPort(), AMBSTemplatedInterface< T >::resetAllPorts(), ambs_calculators::RUNNING, Timer::start_time_, and Timer::TIMED_OUT_.
getNextState()
TimerState getNextState (TimerState current_state) private
Calculate what the next state should be, given current state and external inputs.
The state machine is as follows, always starting from DISABLED: DISABLED -> IDLE IFF ENABLE=True IDLE -> RUNNING IFF START=True RUNNING -> FINISHED IF STOP=True OR (elapsed >= duration) <ANY STATE> -> DISABLED IFF DISABLE=True
Parameters
current_state The state the timer is in now
Returns
The next state the timer should be in
All states can and should transition to DISABLED.
{
  if (control_interface_.getPortMsg(DISABLE_).data)
    return TimerState::DISABLED;
  switch (current_state)
  {
    case TimerState::DISABLED:
    return control_interface_.getPortMsg(ENABLE_).data ? TimerState::IDLE : current_state;
    case TimerState::IDLE:
    return default_control_.getStartMsg().data ? TimerState::RUNNING : current_state;
    case TimerState::RUNNING:
    return default_control_.getStopMsg().data ? TimerState::FINISHED : current_state;
    case TimerState::FINISHED:
    return default_control_.getResetMsg().data ? TimerState::IDLE : current_state;
  }
}
References Timer::control_interface_, AMBSBaseCalculator::default_control_, Timer::DISABLE_, ambs_calculators::DISABLED, Timer::ENABLE_, ambs_calculators::FINISHED, AMBSTemplatedInterface< T >::getPortMsg(), AMBSDefaultCalculatorInterface::getResetMsg(), AMBSDefaultCalculatorInterface::getStartMsg(), AMBSDefaultCalculatorInterface::getStopMsg(), ambs_calculators::IDLE, and ambs_calculators::RUNNING.
Referenced by Timer::executeCB().
init()
void init ()
init function will be called by nodelet manager, so it is not called anywhere from within class
AMBSBaseCalculator::startCalculator() spawns a timer which executes executeCB()
Always start from disabled state
{
  std::vector<std::string> control_inputs{ENABLE_, DISABLE_};
  std::vector<std::string> control_outputs{TIMED_OUT_, INTERRUPTED_};
  control_interface_.init(control_inputs, control_outputs, nh_, node_name_);
  std::vector<std::string> float_inputs{};
  std::vector<std::string> float_outputs{ELAPSED_};
  float_interface_.init(float_inputs, float_outputs, nh_, node_name_);
  debug_logger_.init(nh_, node_name_);
  current_state_ = TimerState::DISABLED;
  debug_states_ = getResolvedParam<bool>(PARAM_DEBUG_, false);
  startCalculator();
  ROS_INFO_STREAM(node_name_ << ": Waiting for Enable");
  if (debug_states_) debug_logger_.logInfo("DISABLED");
}
References Timer::control_interface_, Timer::current_state_, Timer::debug_logger_, Timer::debug_states_, Timer::DISABLE_, ambs_calculators::DISABLED, Timer::ELAPSED_, Timer::ENABLE_, Timer::float_interface_, DebugLogger::init(), AMBSTemplatedInterface< T >::init(), Timer::INTERRUPTED_, DebugLogger::logInfo(), Timer::nh_, AMBSBaseCalculator::node_name_, Timer::PARAM_DEBUG_, AMBSBaseCalculator::startCalculator(), and Timer::TIMED_OUT_.
The documentation for this class was generated from the following file:
ambs_components/include/ambs_components/ambs_calculators/differentiators/timer.h