Automated Modular Benchmarking System: BenchBraking
BenchBraking
Benchmark braking test: analyse braking distance.
#include "bench_braking.h"
Public Member Functions
BenchBraking ()
BenchBraking (ros::NodeHandle nh, std::string node_name)
~BenchBraking () override
void executeCB (const ros::TimerEvent &event) override
Main runner logic, called by the timer. Overrides AMBSBaseRunner::executeCB()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
void mockRobot (const ros::TimerEvent &event)
Mocks the robot & sensor: provides robot speed & sensor location.
Public Member Functions inherited from AMBSBaseRunner
AMBSBaseRunner ()
AMBSBaseRunner (ros::NodeHandle nh, std::string node_name)
virtual ~AMBSBaseRunner ()
Private Member Functions
double getMaxDeviation (std::vector< double > data)
double getStandardDeviation (std::vector< double > data)
Private Attributes
const std::string CALC_BRAKING_DISTANCE_ = "in_calc_braking_distance"
ambs_loggers::DebugLogger debug_logger_
std::vector< std::string > extended_inputs_ {ROBOT_IS_STATIONARY_, ROBOT_HAS_MAX_VEL_}
std::vector< std::string > extended_outputs_ {RESET_TEST}
std::vector< std::string > float_inputs_ {CALC_BRAKING_DISTANCE_}
ambs_base::AMBSTemplatedInterface< std_msgs::Float64 > float_interface_
std::vector< std::string > float_outputs_ {ROBOT_SPEED}
int loops_
ros::Timer mock_robot_
const std::string PARAM_ACCELERATION_ = "acceleration_timeout"
const std::string PARAM_DECCELERATION_ = "decceleration_timeout"
const std::string PARAM_STABILIZATION_ = "stabilization_timeout"
const std::string PARAM_VERIFICATION_ = "verification_timeout"
std::vector< std::string > pose_inputs_
ambs_base::AMBSTemplatedInterface< geometry_msgs::PoseStamped > pose_interface_
std::vector< std::string > pose_outputs_ {ROBOT_LOCATION}
const std::string RESET_TEST = "out_reset_test"
const std::string ROBOT_HAS_MAX_VEL_ = "robot_has_max_vel"
const std::string ROBOT_IS_STATIONARY_ = "robot_is_stationary"
const std::string ROBOT_LOCATION = "out_robot_location"
const std::string ROBOT_SPEED = "out_robot_speed_x"
int sensor_rate_
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseRunner
template<typename T >
T getResolvedParam (std::string param_name)
Gets a specified parameter by resolving to the ambs/runners namespace.
bool initialiseBaseRunner (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs)
Actual initialisation function.
void startRobot ()
void startRunner ()
Starts the timer thread. MUST BE EXPLICITLY CALLED.
void stopRobot ()
void testCompleted ()
Publish test results.
void testFailed ()
Publish test results.
void testSucceeded ()
Publish test results.
std::string timedLoopFallbackOnPorts (std::vector< std::string > *ports, double time, double rate)
Returns the first port in list that has a true message, or if timer expires.
std::string timedLoopSequenceOnPorts (std::vector< std::string > *ports, double time, double rate)
Returns the first port in list that has a false message, or if timer expires.
ambs_msgs::BoolStamped waitForReset ()
Wait for TRUE on the RESET port.
ambs_msgs::BoolStamped waitForStart ()
Wait for TRUE on the START port.
Protected Attributes inherited from AMBSBaseRunner
const std::string DEBUG_TOPIC = "/ambs/debug_messages"
std::string log_folder_path_
std::string log_path_
ros::NodeHandle nh_
std::string node_name_
const std::string PARAM_LOG_FOLDER_ = "/ambs/log_folder"
const std::string PARAM_LOG_ROOT_ = "/ambs/log_folder_root"
const std::string PARAM_ROBOT_NAME_ = "/ambs/robot_name"
const std::string RESET_TEST_ = "in_reset_test"
const std::string ROSBAG_BEGAN_ = "in_rosbag_began"
AMBSBooleanInterface signal_interface_
const std::string START_ROBOT_ = "out_start_robot"
const std::string START_ROSBAG = "out_start_rosbag"
const std::string START_TEST_ = "in_start_test"
const std::string STOP_ROBOT_ = "out_stop_robot"
const std::string TEST_COMPLETED_ = "out_test_completed"
const std::string TEST_FAILED_ = "out_test_failed"
const std::string TEST_SUCCEEDED_ = "out_test_succeeded"
Detailed Description
Benchmark braking test: analyse braking distance.
Constructor & Destructor Documentation
BenchBraking() [1/2]
BenchBraking () inline
{}
~BenchBraking()
~BenchBraking () inline override
{}
BenchBraking() [2/2]
BenchBraking (ros::NodeHandle nh, std::string node_name) inline
                                                     :
     ambs_base::AMBSBaseRunner(nh, node_name)
  {}
Member Function Documentation
executeCB()
void executeCB (const ros::TimerEvent & event) override virtual
Main runner logic, called by the timer. Overrides AMBSBaseRunner::executeCB()
Parameters
event Not used
Implements AMBSBaseRunner.
{
  (void) event;
  std::vector<double> error_list;
  std::vector<double> accuracy_list;
  double error, accuracy, err_avg, acc_avg;
  ros::Duration(1).sleep();
  ROS_WARN_STREAM(node_name_ << "Running bench for " << loops_ << " loops @ "
                  << sensor_rate_ <<"Hz sensor rate");
  std::ofstream debug_file;
  debug_file.open(log_folder_path_ + "/benchmarking.csv", std::ios_base::app);
  debug_file << "TIMESTAMP " << " , " <<
                "ERROR " << " , " <<
                "ACCURACY "<< " , " << std::endl;
  debug_file.close();
  std::chrono::steady_clock::time_point time_begin = std::chrono::steady_clock::now();
  for (int i=1; i <= loops_; i++)
  {
    ROS_INFO_STREAM(node_name_ << "-------------------ITERATION " << i << "--------------------------");
    //  Start mock robot and calcs
    ROS_INFO_STREAM(node_name_ << "Start robot ");
    startRobot();
    //  Wait some time to let robot reach max vel.
    ROS_INFO_STREAM(node_name_ << ": Waiting for tobot to reach max vel");
    timedLoopFallbackOnPorts(new std::vector<std::string>{ROBOT_HAS_MAX_VEL_}, 1000);
    //  Stop mock robot
    ROS_INFO_STREAM(node_name_ << ": Robot maintained max vel, stopping it");
    stopRobot();
    double actual_brake_received = pose_interface_.getPortMsg(ROBOT_LOCATION).pose.position.x;
    ROS_DEBUG_STREAM(node_name_ << ": Starting pos stored @ " << ros::Time::now() <<
                    ": " << actual_brake_received);
    //  Wait for mock robot to actually stop
    ROS_INFO_STREAM(node_name_ << ": Waiting for robot to fully stop");
    timedLoopFallbackOnPorts(new std::vector<std::string>{ROBOT_IS_STATIONARY_}, 1000);
    //  Get braking distance ground truth
    double actual_mock_stopped = pose_interface_.getPortMsg(ROBOT_LOCATION).pose.position.x;
    ROS_DEBUG_STREAM(node_name_ << ": Stopping pos stamp @ "
                    <<  pose_interface_.getPortMsg(ROBOT_LOCATION).header.stamp
                    << " stored @ " << ros::Time::now() <<
                    ": " << actual_mock_stopped);
    double actual_braking_distance = actual_brake_received - actual_mock_stopped;
    //  Wait for result & get calculated braking distance
    ros::Duration(0.5).sleep();
    double calc_braking_distance = float_interface_.getPortMsg(CALC_BRAKING_DISTANCE_).data;
    if (actual_braking_distance == 0)
    {
      ROS_WARN_STREAM(node_name_ << ": 0 braking distance, skipping loop");
      continue;
    }
    error = std::abs(std::abs(actual_braking_distance) - std::abs(calc_braking_distance));
    accuracy = 100 - std::abs(error/actual_braking_distance)*100;
    error_list.push_back(error);
    accuracy_list.push_back(accuracy);
    err_avg = ambs_helper::getMean(error_list);
    acc_avg = ambs_helper::getMean(accuracy_list);
    ROS_DEBUG_STREAM(node_name_ << ": Sens dist: " << actual_braking_distance
                    << " Calc dist " << calc_braking_distance);
    if (accuracy <= 90)
      ROS_ERROR_STREAM(node_name_ << ": BAD Error " << error << " BAD Accuracy " << accuracy);
    else
      ROS_WARN_STREAM(node_name_ << ": Error " << error << " Accuracy " << accuracy);
    ROS_WARN_STREAM(node_name_ << ": Error AVG " << err_avg << " Accuracy AVG " << acc_avg);
    debug_file.open(log_folder_path_ + "/benchmarking.csv", std::ios_base::app);
    debug_file << ros::Time::now() << " , " <<
                  error << " , " <<
                  accuracy << " , " << std::endl;
    debug_file.close();
    //  Reset test
    signal_interface_.publishMsgOnPort(RESET_TEST, signal_interface_.constructNewBoolStamped(true));
    float_interface_.resetAllPorts();
    pose_interface_.resetAllPorts();
    signal_interface_.resetAllPorts();
    //  Randomize next run
    ros::Duration(static_cast<float>(std::experimental::randint(5, 15))/10).sleep();
    ROS_INFO_STREAM(" ");
    ROS_INFO_STREAM("-----------------------------------------------------------");
    ROS_INFO_STREAM(" ");
  }
  std::chrono::steady_clock::time_point time_end = std::chrono::steady_clock::now();
  double time_elapsed = std::chrono::duration_cast<std::chrono::seconds>(time_end - time_begin).count();
  double err_std = ambs_helper::getStandardDeviation(error_list);
  double acc_std = ambs_helper::getStandardDeviation(accuracy_list);
  double err_maxdev = ambs_helper::getMaxDeviation(error_list);
  double acc_maxdev = ambs_helper::getMaxDeviation(accuracy_list);
  ROS_WARN_STREAM(node_name_ << ": AVG Accuracy " << acc_avg <<
                   " STD Accuracy " << acc_std <<
                   " MAXDEV Accuracy " << acc_maxdev);
  ROS_WARN_STREAM(node_name_ << ": AVG Error " << err_avg <<
                   " STD Error " << err_std <<
                   " MAXDEV Error " << err_maxdev);
  debug_file.open(log_folder_path_ + "/benchmarking.csv", std::ios_base::app);
  debug_file << "AVG Accuracy" << " , " << acc_avg << " , " <<
                "STD Accuracy " << " , " << acc_std << " , " <<
                "MAXDEV Accuracy " << " , " << acc_maxdev << std::endl;
  debug_file << "AVG Error" << " , " << err_avg << " , " <<
                "STD Error " << " , " << err_std << " , " <<
                "MAXDEV Error " << " , " << err_maxdev << std::endl;
  debug_file << "Time elapsed (s)" << " , " << time_elapsed << std::endl;
  debug_file << "Loops" << " , " << loops_ << std::endl;
  debug_file << "Sensor rate" << " , " << sensor_rate_ << std::endl;
  debug_file.close();
  ros::shutdown();
}
References BenchBraking::CALC_BRAKING_DISTANCE_, AMBSBooleanInterface::constructNewBoolStamped(), BenchBraking::float_interface_, ambs_helper::getMaxDeviation(), ambs_helper::getMean(), ambs_helper::getStandardDeviation(), AMBSBaseRunner::log_folder_path_, BenchBraking::loops_, AMBSBaseRunner::node_name_, BenchBraking::pose_interface_, AMBSTemplatedInterface< T >::publishMsgOnPort(), BenchBraking::RESET_TEST, AMBSTemplatedInterface< T >::resetAllPorts(), BenchBraking::ROBOT_HAS_MAX_VEL_, BenchBraking::ROBOT_IS_STATIONARY_, BenchBraking::ROBOT_LOCATION, BenchBraking::sensor_rate_, AMBSBaseRunner::signal_interface_, AMBSBaseRunner::startRobot(), AMBSBaseRunner::stopRobot(), and AMBSBaseRunner::timedLoopFallbackOnPorts().
init()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseRunner::startRunner() spawns a timer which executes executeCB()
{
  ROS_INFO_STREAM(node_name_ << ": Init class");
  initialiseBaseRunner(nh_, node_name_, extended_inputs_, extended_outputs_);
  pose_interface_.init(pose_inputs_, pose_outputs_, nh_, node_name_);
  float_interface_.init(float_inputs_, float_outputs_, nh_, node_name_);
  debug_logger_.init(nh_, node_name_);
  loops_ = getResolvedParam<int>("loops");
  sensor_rate_ = getResolvedParam<int>("sensor_rate");
  mock_robot_ = nh_.createTimer(ros::Duration(0.1), boost::bind(&BenchBraking::mockRobot, this, _1));
  startRunner();
}
References BenchBraking::debug_logger_, BenchBraking::extended_inputs_, BenchBraking::extended_outputs_, BenchBraking::float_inputs_, BenchBraking::float_interface_, BenchBraking::float_outputs_, DebugLogger::init(), AMBSBaseRunner::initialiseBaseRunner(), BenchBraking::loops_, BenchBraking::mock_robot_, BenchBraking::mockRobot(), AMBSBaseRunner::nh_, AMBSBaseRunner::node_name_, BenchBraking::pose_inputs_, BenchBraking::pose_interface_, BenchBraking::pose_outputs_, BenchBraking::sensor_rate_, and AMBSBaseRunner::startRunner().
mockRobot()
void mockRobot (const ros::TimerEvent & event)
Mocks the robot & sensor: provides robot speed & sensor location.
Parameters
event Ignored
{
  (void) event;
  int x = 0;
  while (ros::ok())
  {
    if (sin(angles::from_degrees(x)) == 0)
    {
      x++;
      continue;
    }
    geometry_msgs::PoseStamped msg_pos;
    msg_pos.header.stamp = ros::Time::now();
    msg_pos.pose.position.x = sin(angles::from_degrees(x));
    msg_pos.pose.position.y = 0;
    msg_pos.pose.position.z = 0;
    msg_pos.pose.orientation.x = 0;
    msg_pos.pose.orientation.y = 0;
    msg_pos.pose.orientation.z = 0;
    msg_pos.pose.orientation.w = 1;
    pose_interface_.publishMsgOnPort(ROBOT_LOCATION, msg_pos);
    std_msgs::Float64 msg_spd;
    msg_spd.data = sin(angles::from_degrees(x));
    float_interface_.publishMsgOnPort(ROBOT_SPEED, msg_spd);
//    Randomize next run
    x = (x == 360) ? std::experimental::randint(0, 50) : x+1;
    ros::Rate(sensor_rate_).sleep();
  }
}
References BenchBraking::float_interface_, BenchBraking::pose_interface_, BenchBraking::ROBOT_LOCATION, BenchBraking::ROBOT_SPEED, and BenchBraking::sensor_rate_.
Referenced by BenchBraking::init().
The documentation for this class was generated from the following file:
ambs_components/include/ambs_components/ambs_runners/bench_braking.h