Automated Modular Benchmarking System: AMBSDefaultCalculatorInterface
AMBSDefaultCalculatorInterface
A standard boolean AMBSTemplatedInterface interface for calculators.
#include "ambs_default_calculator_interface.hpp"
Public Member Functions
AMBSDefaultCalculatorInterface ()
virtual ~AMBSDefaultCalculatorInterface ()
ambs_msgs::BoolStamped getStartMsg ()
Get the message received by the START_ port.
ambs_msgs::BoolStamped getStopMsg ()
Get the message received by the STOP_ port.
void initDefaultInterface (ros::NodeHandle nh, std::string node_name, std::string in_start, std::string in_stop, std::string in_reset, std::string out_done)
Initialisation decoupled from constructor for convenince.
void printDefaultPorts ()
Print internal buffer values of all ports.
void publishDone ()
Publish TRUE on the DONE port.
ambs_msgs::BoolStamped waitForReset ()
Wait for TRUE on the RESET port.
ambs_msgs::BoolStamped waitForStart ()
Wait for TRUE on the START port.
ambs_msgs::BoolStamped waitForStop ()
Wait for TRUE on the STOP port.
Public Member Functions inherited from AMBSBooleanInterface
AMBSBooleanInterface ()
AMBSBooleanInterface (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs)
virtual ~AMBSBooleanInterface ()
ambs_msgs::BoolStamped constructNewBoolStamped (bool data)
Create a new BoolStamped type message.
ambs_msgs::BoolStamped waitForTrueOnPort (std::string port)
Wait for TRUE on a port.
Public Member Functions inherited from AMBSTemplatedInterface< ambs_msgs::BoolStamped >
AMBSTemplatedInterface ()
AMBSTemplatedInterface (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name)
Constructor.
~AMBSTemplatedInterface ()
ambs_msgs::BoolStamped getPortMsg (std::string port_name)
Gets the latest message received from the port, even if it is not a latched topic.
void init (std::vector< std::string > input_interface, std::vector< std::string > output_interface, ros::NodeHandle nh, std::string node_name)
Initialisation function, decoupled from constructor for convenience.
bool isPortValid (std::string port_name)
Returns if the port has received at least on message.
void printPorts ()
Prints the member fields of the AMBSPorts object of all ports.
void publishMsgOnPort (std::string port_name, ambs_msgs::BoolStamped msg)
Publish a message on a port.
void resetAllPorts ()
Reset inernal buffer message of all ports.
void resetPort (std::string port_name)
Reset internal buffer message of a port.
void setPortMsg (std::string port_name, ambs_msgs::BoolStamped msg)
Sets the internal message value of a port. DOES NOT PUBLISH.
Private Attributes
std::string DONE_
std::string RESET_
std::string START_
std::string STOP_
Additional Inherited Members
Protected Member Functions inherited from AMBSTemplatedInterface< ambs_msgs::BoolStamped >
virtual void templatedCB (const boost::shared_ptr< const ambs_msgs::BoolStamped > msg, std::string topic)
The callback function used by ALL ports.
Protected Attributes inherited from AMBSTemplatedInterface< ambs_msgs::BoolStamped >
std::map< std::string, AMBSPort< ambs_msgs::BoolStamped > > interfaces_
ros::NodeHandle nh_
std::string node_name_
const unsigned int publisher_queue_size_
const unsigned int subscriber_queue_size_
Detailed Description
A standard boolean AMBSTemplatedInterface interface for calculators.
Todo:
Merge this into AMBSBaseCalculator
Useful because all components should have a standard boolean control interface such as start, stop, reset & done
Constructor & Destructor Documentation
AMBSDefaultCalculatorInterface()
AMBSDefaultCalculatorInterface () inline
{}
~AMBSDefaultCalculatorInterface()
virtual ~AMBSDefaultCalculatorInterface () inline virtual
{}
Member Function Documentation
getStartMsg()
ambs_msgs::BoolStamped getStartMsg () inline
Get the message received by the START_ port.
Returns
msg The message
{
  if (isPortValid(START_))
  {
    return getPortMsg(START_);
  }
  else
  {
    return constructNewBoolStamped(false);
  }
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< ambs_msgs::BoolStamped >::getPortMsg(), AMBSTemplatedInterface< ambs_msgs::BoolStamped >::isPortValid(), and AMBSDefaultCalculatorInterface::START_.
getStopMsg()
ambs_msgs::BoolStamped getStopMsg () inline
Get the message received by the STOP_ port.
Returns
msg The message
{
  if (isPortValid(STOP_))
  {
    return getPortMsg(STOP_);
  }
  else
  {
    return constructNewBoolStamped(false);
  }
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSTemplatedInterface< ambs_msgs::BoolStamped >::getPortMsg(), AMBSTemplatedInterface< ambs_msgs::BoolStamped >::isPortValid(), and AMBSDefaultCalculatorInterface::STOP_.
Referenced by EdgeDetector::executeCB(), and CompFloatParam::executeCB().
initDefaultInterface()
void initDefaultInterface (ros::NodeHandle nh, std::string node_name, std::string in_start = "in_start", std::string in_stop = "in_stop", std::string in_reset = "in_reset", std::string out_done = "out_done") inline
Initialisation decoupled from constructor for convenince.
{
  START_ = in_start;
  STOP_ = in_stop;
  RESET_ = in_reset;
  DONE_ = out_done;
  std::vector<std::string> default_inputs{START_, STOP_, RESET_};
  std::vector<std::string> default_outputs{DONE_};
  init(default_inputs, default_outputs, nh, node_name);
}
References AMBSDefaultCalculatorInterface::DONE_, AMBSTemplatedInterface< ambs_msgs::BoolStamped >::init(), AMBSDefaultCalculatorInterface::RESET_, AMBSDefaultCalculatorInterface::START_, and AMBSDefaultCalculatorInterface::STOP_.
Referenced by AMBSBaseCalculator::AMBSBaseCalculator(), DiffFloatTemporal::init(), DiffPoseTemporal::init(), Stopwatch::init(), EdgeDetector::init(), and CompFloatParam::init().
printDefaultPorts()
void printDefaultPorts () inline
Print internal buffer values of all ports.
Used mainly for debugging
{
  ROS_INFO_STREAM("Start : " << std::to_string(getPortMsg(START_).data)
                  << " Stop : " << std::to_string(getPortMsg(STOP_).data)
                  << " Reset : " << std::to_string(getPortMsg(RESET_).data)
                  << " Done : " << std::to_string(getPortMsg(DONE_).data));
}
References AMBSDefaultCalculatorInterface::DONE_, AMBSTemplatedInterface< ambs_msgs::BoolStamped >::getPortMsg(), AMBSDefaultCalculatorInterface::RESET_, AMBSDefaultCalculatorInterface::START_, and AMBSDefaultCalculatorInterface::STOP_.
publishDone()
void publishDone () inline
Publish TRUE on the DONE port.
{
  publishMsgOnPort(DONE_, constructNewBoolStamped(true));
}
References AMBSBooleanInterface::constructNewBoolStamped(), AMBSDefaultCalculatorInterface::DONE_, and AMBSTemplatedInterface< ambs_msgs::BoolStamped >::publishMsgOnPort().
Referenced by Stopwatch::executeCB(), EdgeDetector::executeCB(), CompFloatParam::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
waitForReset()
ambs_msgs::BoolStamped waitForReset () inline
Wait for TRUE on the RESET port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ <<  ": Wait for Reset");
  ambs_msgs::BoolStamped msg = waitForTrueOnPort(RESET_);
  ROS_INFO_STREAM(node_name_ << ": Got Reset");
  resetAllPorts();
  return msg;
}
References AMBSTemplatedInterface< ambs_msgs::BoolStamped >::node_name_, AMBSDefaultCalculatorInterface::RESET_, AMBSTemplatedInterface< ambs_msgs::BoolStamped >::resetAllPorts(), and AMBSBooleanInterface::waitForTrueOnPort().
Referenced by Stopwatch::executeCB(), EdgeDetector::executeCB(), CompFloatParam::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
waitForStart()
ambs_msgs::BoolStamped waitForStart () inline
Wait for TRUE on the START port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ << ": Wait for Start");
  ambs_msgs::BoolStamped msg = waitForTrueOnPort(START_);
  ROS_INFO_STREAM(node_name_ << ": Got Start");
  return msg;
}
References AMBSTemplatedInterface< ambs_msgs::BoolStamped >::node_name_, AMBSDefaultCalculatorInterface::START_, and AMBSBooleanInterface::waitForTrueOnPort().
Referenced by Stopwatch::executeCB(), EdgeDetector::executeCB(), CompFloatParam::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
waitForStop()
ambs_msgs::BoolStamped waitForStop () inline
Wait for TRUE on the STOP port.
Returns
The msg that set TRUE
{
  ambs_msgs::BoolStamped msg = waitForTrueOnPort(STOP_);
  ROS_INFO_STREAM(node_name_ << ": Got Stop");
  return msg;
}
References AMBSTemplatedInterface< ambs_msgs::BoolStamped >::node_name_, AMBSDefaultCalculatorInterface::STOP_, and AMBSBooleanInterface::waitForTrueOnPort().
Referenced by Stopwatch::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
The documentation for this class was generated from the following file:
ambs_core/include/ambs_core/ambs_base_calculator/ambs_default_calculator_interface.hpp