name: ROS melodic CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ambs
          target-ros1-distro: melodic
      - name: Lint_core
        run: |
          cd ~/catkin_ws/src
          catkin build --no-deps ambs_core --make-args roslint
      - name: Lint_components
        run: |
          catkin build --no-deps ambs_components --make-args roslint
      - name: Lint_pluginlib
        run: |
          catkin build --no-deps ambs_pluginlib --make-args roslint

